### ISSUE TITLE
Context should be part of the factory object 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1001]
## Description

We seem to create context directly in commands. This typically should be done thru factory that will allow us to measure some extra metrics/analytics etc.

**Comment by craicoverflow** [comment]
Removing bug label as this is not a bug, it is just something not implemented.

Agreed though - or would it make sense to have it be part of `Connection`?

**Comment by wtrocki** [comment]
It would not be used only for the networking side. 

As for labels. I always get them assigned by default and forget to remove them :D sorry.

**Comment by craicoverflow** [comment]
Ack 😄 

You need to choose "blank issue" or "Feedback", not the "Bug template".

**Comment by alexal** [comment]
@wtrocki assign this to me, please.

**Comment by craicoverflow** [comment]
> Agreed though - or would it make sense to have it be part of Connection?

The reason I mentioned this was because there is a special OAuth context that is available which attaches Bearer tokens to every request. I think we can ignore that for now though.
