### ISSUE TITLE
Add a GitHub Action to output the CLI dependencies to a `vendor` directory.

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1021]
Necessary for productization purposes.

**Comment by wtrocki** [comment]
Can this be done in midstream repo? I had "pleasure" to work with vendored dependencies and it was very challenging to wrap head around - PR's were large due to dependencies being pushed, repository search were hard and overall developer experience doesn't work so well with vendor folder.

**Comment by craicoverflow** [comment]
Yeah, i Had found it a bit tricky to get working in the midstream, having this as a fallback. I should give it another go though soon.

**Comment by wtrocki** [comment]
Do not get me wrong. Do what you need to do, but if there is a way to avoid it lets avoid it
