### ISSUE TITLE
Prefix error messages with "❌"

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1025]
We could prefix all error messages with an "❌" emoji to replace the "Error" prefix.

```shell
$ rhoas kafka use --name kascfkadsfk
❌ Kafka instance "kascfkadsfk" not found. Run the command in verbose mode using the -v flag to see more information
```

This will enhance the visual output of the CLI.

**Comment by wtrocki** [comment]
I like it but we would probably need some community member with windows machine to do it.

**Comment by craicoverflow** [comment]
That is true.
