### ISSUE TITLE
`--verbose/-v` flag is not working in commands with one subcommand

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1034]
## Description

When you run a command which has a single subcommand, the `verbose` flag is ineffective.

Example: run `rhoas login -v`

### Expected vs actual behaviour

Expected behaviour:

```shell
$ rhoas login -v
Refreshing tokens
...
Logging in...
```

Actual behaviour:

```shell
$ rhoas login -v
Logging in...
```

**Comment by rkpattnaik780** [comment]
Happens for other sub-commands as well, e.g not able to see `Starting interactive prompt` for topic and service account create operations.

**Comment by alexal** [comment]
Please see my comments in #1051 but basically debutEnabled is always equals to false because we set it before add a verbose flag.
