### ISSUE TITLE
Explore usage of editor from AlecAivazis/survey instead of custom one

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1036]
We have created a custom editor to modify file contents from the CLI using the user's editor.

This feature also exists in [AlecAivazis/survey ](https://github.com/AlecAivazis/survey#editor), which we are using already in interactive prompts.

It would be better to use this package if possible.

**Comment by wtrocki** [comment]
Apologies. I should have checked survey before. I will take it over and clean things up now

**Comment by wtrocki** [comment]
I found implementation of that inferior to what we have right now. 
It has some bugs (sometimes editor opens for me with empty content - race condition?)
There is requirement to hit enter and after editor opens this enter gets printed etc.

Overal experience is much worse IMHO, but I will try to hack it so we can stop maintaining this custom code.

<img width="1169" alt="Screenshot 2021-09-07 at 11 51 06" src="https://user-images.githubusercontent.com/981838/132337678-c48aa3c5-f5c1-443b-a481-fef7fdb29795.png">

**Comment by craicoverflow** [comment]
Yeah, thanks for investigating, I just saw this while checking their docs and have not tried it myself. Happy to keep as is.
