### ISSUE TITLE
rhoas cluster bind not having any effect

### ISSUE THREAD

**Issue by kabir** [redhat-developer/app-services-cli#1038]
## Description

**Version**: 0.28.0

`rhoas cluster bind` doesn't seem to have any effect.

### Steps to reproduce

1) After running `rhoas cluster connect` it tells me to use `rhoas cluster bind `.
I then try to do that and get an error (the application is not deployed yet):
```
$rhoas cluster bind --app-name reactive-messaging-qs
Namespace not provided. Using microprofile-reactive-messaging-kafka-project namespace
Error: deployments.apps "reactive-messaging-qs" not found. Run the command in verbose mode using the -v flag to see more information
```

2) I then do a `helm install reactive-messaging-qs ...` followed immediately after by `rhoas cluster bind --app-name reactive-messaging-qs`. This time the client appears to succeed, but the service binding does not take effect, and there is no `/bindings` directory on my application pod.

3) I then do a `oc delete servicebinding/my-kafka-xxxx` and see the app pod get bounced.

4) Next I do another `$rhoas cluster bind --app-name reactive-messaging-qs`. The app pod gets bounced, but with the same results as in 2).

### Expected vs actual behaviour

I would expect the service binding to be added, and for there to be a `/bindings` directory on the pods.

This happened with the older version of the CLI, whose `rhoas cluster connect` command spat out some yaml which I applied using `oc apply`.

**Comment by wtrocki** [comment]
@pedjak There seems to be race condition between Binding Operator updating resources and other external updates from helm.  In my mind we cannot do much about it as update happens outside service bininding scope (helm overrides config).

Do we have any recommendations how to handle this cases? Edit binding in order to be reprocessed?

**Comment by pedjak** [comment]
@wtrocki a service binding can be added to the cluster, even if both service and application do not exist at that moment. The operator will try to reconcile and is going to fail, but the binding will be  put back into the queue and recheck after some delay. The delay is going to increase with each next failure exponentially (exponential back off). A lot of details can be found here:

**Comment by wtrocki** [comment]
@pedjak so generally we cannot do much about this problem rather than document it to the end users?

**Comment by pedjak** [comment]
I would rather first deploy both service and application and then add service binding finally.

**Comment by kabir** [comment]
From our side CC @jmesnil that is slightly less friendly to the user than what we did so far which was apply the service binding yaml directly before deploying the application via Helm. Although, you might be right there would have been a delay between the applying of the service binding and deploying the application.

**Comment by jmesnil** [comment]
imho, the service binding should not be dependent on the order of creation go the services and the binding requests.

Would it be possible for the service binding operator to trigger reconciliation without rate limitation when one or both of the resources to binds are not present?
I suspect this is treated as an error (thus triggering an exponential backoff) while this is a typical use case. There might be quite some time between a KafkaConnection being added to the cluster (and the service binding request is created at that time iiuc) and an app that used it being deployed on the cluster.

**Comment by kabir** [comment]
@Jeff the connect and the service binding is actually a two phase thing

1) `rhoas kafka connect`
2) oc apply the service binding - which is now replaced by a `rhoas bind` (oc apply still works)

Then we deploy the application, but still I think the gist of why at you say is how it should ideally work. This is why we rewrote the QS to use Helm since with the oc apply service binding approach it just worked.

With the non-Helm approach (oc new-app...) the user would deploy a not working version of their application, then have to apply the service binding, the non-working application pod got taken down and a new working application pod is brought up. That is effectively what we will end up with the new rhoas bind approach in its current form.

**Comment by pedjak** [comment]
> imho, the service binding should not be dependent on the order of creation between the services and the binding request.

And it does not. We have a number of tests verifying that. The time for retry after each failure get doubled, but it is limited to 1000 seconds. SBO does not give up so quickly, but I might be that it does not try to reconcile so often after a while.

> There might be quite some time between a KafkaConnection being added to the cluster (and the service binding request is created at that time iiuc) and an app that used it being deployed on the cluster.

After several attempt to bind, the next reconciliation would be retried in cca 16mins or so, and then at that rate. Can you confirm that binding does not happen within 30mins after the application resource is created?

> With the non-Helm approach (oc new-app...) the user would deploy a not working version of their application, then have to apply the service binding, the non-working application pod got taken down and a new working application pod is brought up. That is effectively what we will end up with the new rhoas bind approach in its current form.

That is perfectly ok from kubernetes point of view. Kubernetes can take down pods at any point in time and restart them. The application should be able to handle that, or wrong/missing configuration.

**Comment by kabir** [comment]
> Can you confirm that binding does not happen within 30mins after the application resource is created?
Actually I see that I have confused this with my other issue #1039 which is more concerned with the ordering.
The issue for this one is that `rhoas bind` does not seem to do anything  :)

I've tried:
1) `rhoas cluster connect ...`
2) `helm deploy ....` to get a 'broken app' (no /bindings directory)
3) `rhoas cluster bind ...` - this takes down the pod and reloads it, which again causes problems

I think the I see what the problem is. When I inspect the pod after 3) I see a `/bindings/kabir-kafka-4a92` directory. In our configuration we point at `/bindings/kabir-kafka` to populate our (WildFly) configuration. 

Since the name of the directory is unknown we cannot do anything right now. We have a RFE to point to a root directory for bindings (i.e. all under `/bindings`) but that can not come in for another few months due to our product lifecycle rules. So, I think for now we will just have to use the service binding yaml, which ends up as simply `/bindings/kabir-kafka`

**Comment by kabir** [comment]
Correction: earlier the service binding name was `kafka-config` (not `kabir-kafka`)which was the name of the binding spat out from `rhoas cluster connect` command. The current `kabir-kafka-xxxx` is from the name of the kafka cluster. 

I see a `--binding-name` argument to `rhoas kafka bind` which seems to be the resulting `/bindings` directory sub folder. I will correct this to `--binding-name=kafka-config` and see what happens.

**Comment by kabir** [comment]
Cool, so with `rhoas cluster bind --app-name=reactive-messaging-qs --binding-name=kafka-config` it works as it used to do.

**Comment by wtrocki** [comment]
We are planning to improve bind command in the next release. Thank you for the discussion points

**Comment by wtrocki** [comment]
There were changes in SBO, CLI and Operator since then that will make this issue go away. SBO has now hook that validates creation of the CR. CLI will handle that hook with proper message. Closing but we can reopen if there is something we missed

**Comment by kabir** [comment]
@wtrocki is there some issue/ticket I can watch? I'd love to try out if the way I would like this to work works once this is live. Or are you saying this is there already?

**Comment by wtrocki** [comment]
0.10.0 version of SBO operator should have validation enabled. I could not find issue for that but I have experienced this feature when trying to replicate this use cases.
