### ISSUE TITLE
Dry run mode for bind

### ISSUE THREAD

**Issue by kabir** [redhat-developer/app-services-cli#1039]
### Feature or problem description
@wtrocki asked me to open this, but the jargon is new to me so the title might be wrong.

Currently if I try to run `rhoas bind` before deploying an application, I get an error:
```
$rhoas cluster bind --app-name reactive-messaging-qs
Namespace not provided. Using microprofile-reactive-messaging-kafka-project namespace
Error: deployments.apps "reactive-messaging-qs" not found. Run the command in verbose mode using the -v flag to see more information
```

### Proposed solution

It would be nice to have a mechanism (possibly with a dry-run/lenient/force flag?) to be able to add the service binding before deploying the application.

How will it benefit the CLI and its users?
Essentially with the old way of registering the service binding using the YAML returned by `rhoas cluster connect`, you were able to specify the application name before deploying the application. Once you deployed the application, the service binding would get picked up. This was nice for quickstarts since you could do all the rhoas commands to login, choose the Kafka instance, connect to the cluster, and finally add the binding in one block of rhoas commands before moving on to other things.

### Additional context

Add any other context like screenshots or mockups, if applicable.

**Comment by wtrocki** [comment]
@kabir Thank you for reporting issue. I think this is good idea but we need to call out general strategy for bind command in the CLI

**Comment by wtrocki** [comment]
Thank you so much for your feedback. We have used this feedback to propose solution on SBO side that invalides SBO dry mode. There is no way now to create invalid CR on SBO side. If you feel that we missed something lets reopen
