### ISSUE TITLE
rhoas kafka create - 429 Too Many Requests

### ISSUE THREAD

**Issue by alexal** [redhat-developer/app-services-cli#1057]
Right now, if you have created one Kafka instance and try to create another one, you will get the following error

```
/private/var/folders/s6/dqhzqm7x2gb8vlvskw4jqj380000gn/T/GoLand/___rhoas_kafka_create kafka create
? Name: test1
? Cloud Provider: aws
? Cloud Region: us-east-1
❌ 429 Too Many Requests. Run the command in verbose mode using the -v flag to see more information
```

With -v flag enabled, you will see the actual reason of 429 error

`{"id":"24","kind":"Error","href":"/api/kafkas_mgmt/v1/errors/24","code":"KAFKAS-MGMT-24","reason":"only one eval instance is allowed","operation_id":"c4tal4oc3kjol9oa6a0g"}`

However, my question is, should we improve the error message?

**Comment by wtrocki** [comment]
we should

**Comment by craicoverflow** [comment]
Yes. Myself and @wtrocki were discussing options on how to reliably check the meaning of the error codes from the backend.

I think in the meantime though we should print the error "reason" from the backend.

**Comment by wtrocki** [comment]
@craicoverflow I do that already in registry (using helper to cast to APIError). Plan was to also do the same for kafka. +1 from me

**Comment by craicoverflow** [comment]
Agreed.

**Comment by craicoverflow** [comment]
> @craicoverflow I do that already in registry (using helper to cast to APIError). Plan was to also do the same for kafka. +1 from me

I'm seeing some cases where this is not being done. Maybe it is not applied everywhere?

```shell
❯ ./rhoas service-registry create --name enda-dev
Creating Service Registry with name: enda-dev
Error: 500 Internal Server Error. Run the command in verbose mode using the -v flag to see more information
```

**Comment by wtrocki** [comment]
Yes.. Registry artifacts only for now

**Comment by alexal** [comment]
@craicoverflow, @wtrocki I would love to work on this problem.

**Comment by craicoverflow** [comment]
Sure thing @alexal. It is a good idea to suggest a couple of ways to address this problem as the way to implement it is not trivial.

We can converse on this issue until a collective agreement is made. This can save you time in the long run and help build a better solution :)

**Comment by wtrocki** [comment]
There is couple problems here:

- SDK should have common APIError object that can be used to cast error coming from API. 
This way we can provide generic method to read reason

- Each SDK should map the error code - handling for that will be in SDK - I'm doing some preliminary work to enable that. 

This needs more across the board work, but it is high on our priority list.

**Comment by craicoverflow** [comment]
@alexal has a good approach for the short term in https://github.com/redhat-developer/app-services-cli/pull/1064 - however I think we need to handle this in `main.go`. A switch statement which performs a type check for the error codes from each services.

This psuedocode is kind of what I was thinking).
````go
switch {
  case KafkaMGMTError:
  case ServiceRegistryMGMTError:
  case OtherSrerviceError:
	fmt.Print(err.Reason())
}
```

When the time comes and we have access to error codes we should handle these individually in commands. but this can be used as a fallback and catch any ones which have not been handled.

thoughts @wtrocki ?

**Comment by wtrocki** [comment]
```
switch {
  case KafkaMGMTError:
  case ServiceRegistryMGMTError:
  case OtherSrerviceError:
	fmt.Print(err.Reason()
```

This is ok but there is common Error class that is in every SDK right now so my proposal was to always return some error interface and rely on the same `code` and `reason` field. 


Our error handling should be:

- Local in case of specific error codes that we expect from backend - LIke terms not accepted.
- Global as you have suggested for cases of other stuff we do not predict specifically 400 and 500 mostly. 

We should also try to use error codes more (I have separate issue for that for registry and kafka is already doing good job on that front)

**Comment by alexal** [comment]
@wtrocki I see Error struct (I'm already using it in the proposed code), but not the interface. Could you please point me to the class you was talking about?

**Comment by wtrocki** [comment]
I will go step by step. Do what enda proposed. then we can improve sdk

**Comment by alexal** [comment]
> I will go step by step. Do what enda proposed. then we can improve sdk

Something like this https://github.com/redhat-developer/app-services-cli/pull/1064/commits/d7e678bbac328fa483600f5a828042f448b3e8cf ?

**Comment by wtrocki** [comment]
Yes. good starr

**Comment by alexal** [comment]
![image](https://user-images.githubusercontent.com/499857/133138256-a5b69e67-a2bc-4100-9ac4-0247e697d92f.png)

**Comment by alexal** [comment]
I've added two more registryinstanceclient & registrymgmtclient

![image](https://user-images.githubusercontent.com/499857/133142430-c0f42829-7bc8-47fd-8d39-c9a40c0f1ab6.png)

**Comment by craicoverflow** [comment]
> We can now solve nr1 fairly easy by casting to kafka.ApiError (as generally each APIError should look the same)

Unless we strictly enforce that, then not all error objects are the same. Data plane APIs do not conform to the api.openshift.com standards. It may maybe sense so have an error casting helper in every individual SDK, in Go especially since they are independent. This can also future proof the SDK from breaking changes if the error type from differetn SDKs diverge.

**Comment by craicoverflow** [comment]
> @wtrocki I see Error struct (I'm already using it in the proposed code), but not the interface. Could you please point me to the class you was talking about?

Go does not have the concept of a "class", a struct is the closest thing to a class though.

**Comment by wtrocki** [comment]
I'm going to start with fixing SDK's but assigning this area to CLI. there will be a lot of changes in CLI needed to incorporate this so we might later split to separate issues.

**Comment by wtrocki** [comment]
@craicoverflow this is up to grabs
