### ISSUE TITLE
Make all `Options` in commands private

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1058]
The Options type in every command is public. This was originally done at the beginning with the anticipation is being used in tests, but since there is no need anymore, we can make all options private now.

**Comment by alexal** [comment]
I will work on this.

**Comment by wtrocki** [comment]
Options is also bad name. Wdyt about `inputArgs`

**Comment by craicoverflow** [comment]
`args` is good.

**Comment by craicoverflow** [comment]
Out of curiosity, why is it a bad name?
