### ISSUE TITLE
Remove shortcuts from artifacts commands

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1062]
We need to remove -a from +5 commands

_Originally posted by @wtrocki in https://github.com/redhat-developer/app-services-cli/pull/1054#discussion_r706049719_

**Comment by alexal** [comment]
I didn't see that this issue was assigned already, sorry :-)

**Comment by wtrocki** [comment]
@alexal no worries. Typically labels `needs-triage` are off the grid for taking as we need to discuss them, but this one was obvious.  Seen your PR - good job
