### ISSUE TITLE
Improvements in the `dump` package

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1067]
The `PrintDataInFormat` method could do with some minor changes to improve it.

- [ ] Change the name to something cleaner, and shorter. `DumpFormatted` is my preferred (fewer words used), I am open to other suggestions.
- [ ] The `io.Writer` parameter always comes first in a Go method which uses that writer. Let's put it first here too.
- [ ] Return an error if any from this method. We should not be ignoring errors here. It is up to the method usage to decide whether to use the error or not, it should be returned.
- [ ] Create a special type `DumpFormat` and set the constants `XFormat` constants to use this format (nice to have, not needed though). This means we can limit the valid values for `format` used in `PrintDataInFormat`.

**Comment by alexal** [comment]
I propose to use just `Formatted` as the function name to remove package name duplication from it.

**Comment by alexal** [comment]
@craicoverflow I did everything except the last item. Could you please provide more information about it?

**Comment by craicoverflow** [comment]
```go
type OutputFormat = string

const JSONFormat OutputFormat = "json"
```
