### ISSUE TITLE
Period at the end of the token prevents users from visiting token page

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1069]
### Feature or problem description

Period at the end of the token prevents users from visiting token page.
Should we enable opening browser window automatically with the token page?

> Feedback from tooling team

**Comment by craicoverflow** [comment]
> Should we enable opening browser window automatically with the token page?

The user could be in a headless environment so we would need to cater for that. We could auto-open the browser but I feel that there should also be an option to not do this.

**Comment by craicoverflow** [comment]
Also - if the user is using console.redhat.com in a private window, or their non-default browser then I think the default browser will always open, which is a slight nuisance.

**Comment by wtrocki** [comment]
> The user could be in a headless environment so we would need to cater for that. 

Headless environments use --token. This problem happens in interactive mode that will not be enabled in headles mode.
