### ISSUE TITLE
Incorrect prompt text for `rhoas kafka use`

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1074]
```shell
$ rhoas kafka use
? Select Kafka instance to connect: my-kafka
```

Select Kafka instance to "connect" is inacxcurate. I believe this is being used also in the `cluster connect` command. We need a distinct prompt title which relates to "using" an instance.

**Comment by alexal** [comment]
As InteractiveSelect() function is used in the multiple places, maybe it is easy just to change a text message to "Select Kafka instance"?

**Comment by craicoverflow** [comment]
Yes, I like that :)
