### ISSUE TITLE
Create a custom linter which can detect if a i18n message ID does not exist.

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1076]
I think it is entirely possible for us to create a custom linter which can be included as part of `golanci-lint` which can detect missing i18n message IDs and fail the build.

When `MustLocalize` or `MustLocalizerError` are used, the linter would look up the i18n locales directory and try to find the ID. If it does not exist, the linter would throw and error.

We can create a private linter by following these docs: https://golangci-lint.run/contributing/new-linters/#how-to-add-a-private-linter-to-golangci-lint

**Comment by alexal** [comment]
Interesting, I would love to work on this.

**Comment by wtrocki** [comment]
@alexal I have done some experiments for that already using golang ast:

https://www.zupzup.org/go-ast-traversal/

**Comment by craicoverflow** [comment]
Nice! Check out this document on how to get started adding a private linter: https://golangci-lint.run/contributing/new-linters/#how-to-add-a-private-linter-to-golangci-lint

**Comment by alexal** [comment]
Thanks for the useful links. I will check them out, please assign this issue to me.

**Comment by alexal** [comment]
@wtrocki , @craicoverflow here are the results from the first working prototype. I'm still working on it, just want to show the progress. If you do not mind keeping those strings untranslated for some time, as I'm using app-services-cli project for testing with large number of files (go as well as toml).
```
❯ time ./go-i18n-linter ./...
/Users/Alex/Dev/app-services-cli/pkg/cmd/kafka/topic/list/list.go:73:45: Translation string 'kafka.common.page.error.invalid.minValue' doesn't exist
/Users/Alex/Dev/app-services-cli/pkg/cmd/kafka/topic/list/list.go:77:45: Translation string 'kafka.common.size.error.invalid.minValue' doesn't exist
/Users/Alex/Dev/app-services-cli/pkg/cmd/login/login.go:102:50: Translation string 'login.log.info.sshLoginDetected' doesn't exist
./go-i18n-linter ./...  4.89s user 3.36s system 489% cpu 1.686 total
```

**Comment by craicoverflow** [comment]
This is really really cool @alexal 🎆

**Comment by wtrocki** [comment]
Nice!

**Comment by alexal** [comment]
@wtrocki , @craicoverflow I'm almost done. The linter itself is working just fine, I'm working on updating the README now. I just want to check with both of you. What is the preference here in terms of delivering it? Try to push that new linter to golangci-lint repo or create a private linter plugin?

**Comment by craicoverflow** [comment]
This won't have any usage outside of this repo since it is coupled to our custom Localizer interface so it should be private. Perhaps in the future it could become its own thing :)

**Comment by wtrocki** [comment]
We can contribute that interface back to the upstream and propose linter there - author looks for contributors etc.

**Comment by alexal** [comment]
Looks like I have to use go version 1.15 when building the plugin.

**Comment by alexal** [comment]
The plugin is definitely working once I use it with golangci-lint that I built locally

![image](https://user-images.githubusercontent.com/499857/134503629-c50509e2-1c46-40a7-a189-903a7174737f.png)

@wtrocki, @craicoverflow do you have any ideas on how to resolve this problem? Do we need to build our own golangci-lint?

**Comment by craicoverflow** [comment]
> The plugin is definitely working once I use it with golangci-lint that I built locally
> 
> ![image](https://user-images.githubusercontent.com/499857/134503629-c50509e2-1c46-40a7-a189-903a7174737f.png)
> 
> @wtrocki, @craicoverflow do you have any ideas on how to resolve this problem? Do we need to build our own golangci-lint?

I think if you open a draft PR with the current changes we might be able to try it out and help with a solution.

**Comment by wtrocki** [comment]
Closing as this was done. We need to merge the changes. I believe that @rkpattnaik780 was looking into that.
