### ISSUE TITLE
Missing URL to UI

### ISSUE THREAD

**Issue by fvaleri** [redhat-developer/app-services-cli#1085]
Suppose I created my SR instance/tenant:

```sh
$ rhoas service-registry create --name greeting-test
{
  "created_at": "2021-09-17T14:23:20Z",
  "href": "/api/serviceregistry_mgmt/v1/registries/72cf6425-08bf-4879-8483-7e4046b46715",
  "id": "72cf6425-08bf-4879-8483-7e4046b46715",
  "kind": "ServiceRegistry",
  "name": "greeting-test",
  "owner": "user-test",
  "status": "accepted",
  "updated_at": "2021-09-17T14:23:20Z"
}
```

Now, I have no idea how to access the web UI, for example to set artifact's policies.

Ideally, I would get the web UI URL in the previous response, but also in the output of`rhoas service-registry list`.

**Comment by wtrocki** [comment]
@EricWittmann @jsenco - WDYT about having harcoded url to UI returned from SRS backend? I can create issue on SRS side and contribute back that change. It is more about what do you think?

If we hardcode that we going to have invalid URL for QA env but that is something that is not going to affect users etc.

**Comment by wtrocki** [comment]
@jsenko

**Comment by EricWittmann** [comment]
We shouldn't hardcode the URL.  It's easy enough to make it configurable.  Then it works in both environments.

**Comment by wtrocki** [comment]
@EricWittmann thank you for tracking this issue. We will update CLI once url is returned by backend

**Comment by jsenko** [comment]
So the idea is to add a new field, e.g. `ui_url` to the response?

**Comment by EricWittmann** [comment]
I like `browser_url` or `ui_url`.  But all good choices. :)

**Comment by wtrocki** [comment]
FYI
I see this merged on backend and have this supported in the SDK but still do not see this field returned.

**Comment by EricWittmann** [comment]
Hasn't been deployed to staging yet.  Pipelines are failing.

**Comment by wtrocki** [comment]
Works like drem! thank you so much team for doing this! Experience is totally different right now

**Comment by fvaleri** [comment]
Thanks guys for the quick turnaround. This is a small thing that will really improve the user experience.
