### ISSUE TITLE
For the `update` commands, do not display the updated object as JSON by default.

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1092]
Running `rhoas kafka topic update` will by default print the topic configuration to stdout. This is a massive object and it is unlikely that the user needs to see it. We should default to printing a simple success message by default, and allow users to use the output flag to output the object.

**Comment by craicoverflow** [comment]
@rkpattnaik780 @wtrocki thoughts on this?

**Comment by wtrocki** [comment]
+1. I had the same question on service registry and settled with message instead of printing json

**Comment by craicoverflow** [comment]
Something like the following would be good:

```
Kafka instance {{Name}} updated successfully. Run "rhoas kafka describe --name {{Name}} to view configuration details."
```
