### ISSUE TITLE
Add validation for service account/user roles in service registry role commands

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1095]
### Feature or problem description

 Add validation for service account/user roles in service registry role commands.

service-registry role add command should validate service account name and username provided by CLI before creating rules

**Comment by wtrocki** [comment]
I believe that we track that in the epic created by @craicoverflow . Can you confirm?

**Comment by craicoverflow** [comment]
I'm unaware of such a thing. Maybe @rkpattnaik780 knows?

**Comment by wtrocki** [comment]
I have created requirement to cross team epic. Please disregard
