### ISSUE TITLE
`rhoas docs` command to generate documentation in multiple formats

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1098]
### Feature or problem description

I want to be able to generate documentation files locally in multiple formats. Currently, running the root command along with `GENERATE_DOCS=true` will generate documentation in Asciidoc format. Ideally we should be able to generate Markdown and Man pages also.

I mainly need to generate Man docs for official builds.

### Proposed solution

`rhoas docs -o ./docs --format=md,adoc,man`.

If needed, this can be enable only with `RHOAS_DEV=true` since users will probably not use this often or ever.

**Comment by wtrocki** [comment]
Amazing idea! this way we can have upstream documentation
