### ISSUE TITLE
CLI Guidelines: Arguments and Flags

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1100]
Create CLI guidelines section that will cover arguments and flags (separate md file)

- Arguments (patterns and descriptions)
- Flags (patterns and descriptions)
- List common flags in used in CLI (--yes, --output-file, --output etc)
- Default values

See https://clig.dev/#arguments-and-flags for inspiration

**Comment by wtrocki** [comment]
This seems out of place. We should probably create some epic/general issue with context or add context to each issue created.
We need to triage it as well

**Comment by craicoverflow** [comment]
There is a milestone: https://github.com/redhat-developer/app-services-cli/milestone/8

The idea of having multiple issues was to allow multiple people to work on the different sections.

**Comment by wtrocki** [comment]
Perfect. I have updated issue to explain things better. Feel free to copy it over.
