### ISSUE TITLE
`rhoas status` not displaying service registry status by default

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1109]
### Feature or problem description

`rhoas status` status command should display status of service-registry instance by default.

### Proposed solution

Add `service-registry` to list of allowed services and remove dev preview check.

**Comment by rkpattnaik780** [comment]
Cc @wtrocki

**Comment by wtrocki** [comment]
@rkpattnaik780 totally forgot about this extra check. Adding it now
