### ISSUE TITLE
`rhoas service-registry use` not working with interactive mode

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1110]
## Description

`rhoas service-registry use` fails with `Unable to list Service Registry instances: 500 Internal Server Error. Run the command in verbose mode using the -v flag to see more information`

```
{"id":"1","kind":"Error","href":"/api/serviceregistry_mgmt/v1/errors/1","code":"SRS-MGMT-1","reason":"Unspecified error"}
```

### Steps to reproduce

1. Run rhoas service-registry use interactively:
```
./rhoas service-registry use
```
2. It should throw the error
```
Unable to list Service Registry instances: 500 Internal Server Error. Run the command in verbose mode using the -v flag to see more information.
```

### Expected behaviour

Should prompt existing instance names to choose from.

### Logs

![Screenshot from 2021-09-23 18-13-51](https://user-images.githubusercontent.com/23582438/134509075-736ae8fb-0b28-4391-94c6-d280a3a48dcc.png)

**Comment by wtrocki** [comment]
Done! good catch!
