### ISSUE TITLE
Client side validation for `rhoas service-registry list`

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1111]
## Description

CLI should validate inputs provided for flags `--page` and `--limit`.

Providing a non-positive value throws error 500 with reason `Unspecified error`

### Steps to reproduce

1. Run service-registry list command with limit = 0.
```
./rhoas service-registry list --limit 0 
```

### Expected behaviour

Client should throw error that positive values are to be provided.

### Logs

![Screenshot from 2021-09-23 18-26-48](https://user-images.githubusercontent.com/23582438/134510835-e184808d-e877-408d-9349-b6e84eac3605.png)

**Comment by wtrocki** [comment]
We need the same for kafka.

**Comment by amoghrajesh** [comment]
@wtrocki @rkpattnaik780 I am relatively new to OSS and would like to give this issue a shot. Let me know how I can onboard myself with this and where I can look for the code to change

**Comment by rkpattnaik780** [comment]
> @wtrocki @rkpattnaik780 I am relatively new to OSS and would like to give this issue a shot. Let me know how I can onboard myself with this and where I can look for the code to change

Thanks @amoghrajesh ! You would need to make changes to the file `pkg/cmd/registry/list/list.go`.
You can have a look at how `topic list` validates the flags.

**Comment by amoghrajesh** [comment]
@rkpattnaik780 I have created a patch that will handle this fix as a part of https://github.com/redhat-developer/app-services-cli/pull/1163.
Please have a look and review it, thanks!
