### ISSUE TITLE
Artifact name goes missing for any type other than OPENAPI

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1117]
## Description

If we create artifacts of type AVRO and OPENAPI using same json input file, name gets lost for type AVRO.
It can be later provided/modified using `set-metadata`. Is this expected?

### Steps to reproduce

1. Create two different artifacts of type OPENAPI and AVRO using the same input file (which must contain value for `info.title`.
2. `rhoas artifact list` should show both the created artifacts but name will be available for only one of them.

**Comment by wtrocki** [comment]
@rkpattnaik780 avro should have different format/content so we should not be using the same file. 
If we use OpenAPI file that will be openapi - and it should be autodetected. If we use Avro it should be the same.

**Comment by rkpattnaik780** [comment]
> @rkpattnaik780 avro should have different format/content so we should not be using the same file.
> If we use OpenAPI file that will be openapi - and it should be autodetected. If we use Avro it should be the same.

Thanks for the clarification. Closing this issue.
