### ISSUE TITLE
`rhoas service-registry artifact state-set` should have `--state` flag as required

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1120]
## Description

Omitting `--state` flag for `rhoas service-registry artifact state-set` throws error "Invalid value '' for ArtifactState: valid values are [ENABLED DISABLED DEPRECATED]."

### Steps to reproduce

1. Run artifact state-set command without `--state` flag
```
./rhoas service-registry artifact state-set --artifact-id sasori-38 --group custom 
```
2. It should throw the error:
```
Invalid value '' for ArtifactState: valid values are [ENABLED DISABLED DEPRECATED]. Run the command in verbose mode using the -v flag to see more information
```

### Expected vs actual behaviour

The error should be flag is compulsory rather than invalid value provided.

### Logs
![Screenshot from 2021-09-23 20-15-26](https://user-images.githubusercontent.com/23582438/134529289-6f626c01-47cf-4d9b-9ae3-e53cbaf66290.png)

**Comment by wtrocki** [comment]
Awesome! Ugly bug or can be just request for interactive mode :)

**Comment by wtrocki** [comment]
Done
