### ISSUE TITLE
Use cobra methods to mark flag as required

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1121]
## Description

Certain commands manually check if flag is provided using if statements.

Example: pkg/cmd/registry/artifact/state/state.go

```
if opts.artifact == "" {
	return f.Localizer.MustLocalizeError("artifact.common.message.artifactIdRequired")
}
```

A better approach:

```
_ = cmd.MarkFlagRequired("artifact-id")
```

**Comment by wtrocki** [comment]
I question if that is better. Provided approach using non i18n format that cannot be controlled or changed by docs team.

**Comment by rkpattnaik780** [comment]
> I question if that is better way. Provided approach using non i18n format that cannot be controlled or changed by docs team.
> Maybe we want our own helper for that that uses i18n.

This could be a good topic for discussion, we should zero in on one approach and follow it throughout.

**Comment by craicoverflow** [comment]
Using the built-in `MarkFlagRequired` ensures that Bash completions are aware that this is a required flag I think.

```
// MarkFlagRequired instructs the various shell completion implementations to
// prioritize the named flag when performing completion,
// and causes your command to report an error if invoked without the flag.
```

**Comment by wtrocki** [comment]
Good point. We need to investigate if we can change message for err in this case etc. :D

**Comment by wtrocki** [comment]
Outdated.
