### ISSUE TITLE
User should be able to specify their own service account when doing cluster connect

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1123]
## Description

User should be able to specify their own service account when doing cluster connect.
We should be able to reuse service account (if it is there) and allow user to specify their own if needed.

**Comment by wtrocki** [comment]
One of the requirements comming from jira/@DuncanDoyle

**Comment by wtrocki** [comment]
Approved by @DuncanDoyle

**Comment by wtrocki** [comment]
I guess this is up to discussion but we need 2 new flags

**Comment by craicoverflow** [comment]
Yep and I think it is an important discussion. Realistically the most secure way is loading it from the file, but we have JSON, env and properties file formats. It will be simple enough to load from JSON, I'm not sure about the others though.

**Comment by wtrocki** [comment]
Adding this to technical call next week

**Comment by wtrocki** [comment]
Tracked in jira
