### ISSUE TITLE
Limit the use of "Run the command in verbose mode using the -v flag to see more information" in error messages

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1136]
All error messages currently have the message "Run the command in verbose mode using the -v flag to see more information" at the end, but realistically this should be limited to certain cases like backend errors.

**Comment by wtrocki** [comment]
+1 but would lets not do it in near term - will collide with error handling discussion we need to have. I got feedback that this message is very useful

**Comment by wtrocki** [comment]
I added that as acceptance criteria to error handling epic
