### ISSUE TITLE
RHOAS CLI update commands fail on automation due to missing output flag 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1140]
## Description

We need to adjust automation to perform extra queries to get json output
![Screenshot 2021-09-27 at 11 40 55](https://user-images.githubusercontent.com/981838/134893625-cf27e67b-2240-4961-b7b4-247104ef9b36.png)

**Comment by craicoverflow** [comment]
there is a PR in the tests repo for this. Closing.
