### ISSUE TITLE
Generated service account is missing auth url required for service registry

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1144]
## Description

For service registry, we need a token url (SSO) to be included for users to be able to configure their registry configuration manually. 
UI already does that right now. CLI is missing it so we need this ASAP (and provide new release)
![Screenshot 2021-09-27 at 16 49 02](https://user-images.githubusercontent.com/981838/134942335-a8211c0e-e98a-4fc0-83dd-35ff4b80c0f7.png)

URL:
https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token

**Comment by wtrocki** [comment]
We need some way to differentiate between QA and Prod

**Comment by wtrocki** [comment]
@craicoverflow @rkpattnaik780 - WDYT about adding "token_endpoint_url" field to the output file?

**Comment by rkpattnaik780** [comment]
> @craicoverflow @rkpattnaik780 - WDYT about adding "oauth_token_endpoint_url" field to the output file?

Sounds fine, but will it be better if we display it in STDOUT rather than printing it to a file?

**Comment by wtrocki** [comment]
env file can be used in guides/will work out of the box when cli print out will be more manual

**Comment by craicoverflow** [comment]
Writing the token endpoint URL will actually be better that having some separate command or flag to print it in my opinion.

The currently credentials files offer no context as to the environment they are valid for. This makes it difficult for the user to associate the credentials with the correct environment without using `service-account describe`.

We could always offer both options? `rhoas service-account describe --token-endpoint-url` as well as printing it to a file.

**Comment by wtrocki** [comment]
Done
