### ISSUE TITLE
ServiceRegistry and Kafka list commands should print what Kafka instance is currently used 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1145]
## Description

ServiceRegistry and Kafka list commands should print what Kafka instance is currently used:

```
rhoas service-registry list
```

Might need new column or even * to mark registry as currently used in CLI

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue. Please guide me further ^_^

**Comment by wtrocki** [comment]
list.go file has logic for listing service registry. 
I will start with adding `*` to first component and create pr. Then we can use logic from use.go to get kafka that is selected

**Comment by alexal** [comment]
@wtrocki I just created a new PR, please review and let me know if you want to change anything. Here is how it looks:

![image](https://user-images.githubusercontent.com/499857/136080277-77a34e84-21e5-4c2d-9b9b-fca56c845b54.png)

I do not have access to create more than one Kafka or Service Registry instance, thus I have only one in the list.

**Comment by rkpattnaik780** [comment]
Probably a better layout could be to highlight the instance name and add a "*". Similar to how we get in `git branch`. Adding a column introduces a lot of empty spaces. Wdyt @wtrocki

**Comment by craicoverflow** [comment]
I agree @rkpattnaik780 - I was thinking the same. Perhaps something like `alexal (current)`? An asterisk does not explain the meaning.

**Comment by craicoverflow** [comment]
The text is neater. Could you put it _after_ the name instead though? Maybe share a screenshot of that and we can compare.

**Comment by alexal** [comment]
Like this?

![image](https://user-images.githubusercontent.com/499857/136205223-eeaeb606-dfd5-4e10-8b91-b7f36530a89a.png)

**Comment by alexal** [comment]
I've pushed the changes.

**Comment by rkpattnaik780** [comment]
> Yes, looks good 👍🏻 @rkpattnaik780 @wtrocky do you like?

This looks good!
