### ISSUE TITLE
Use validator library to validate timestamp offset value

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1147]
## Description

**Version**: 0.31.0

Use an iso8601 validator lib to validate value provided for timestamp input.

Originally discussed [here](https://github.com/redhat-developer/app-services-cli/pull/876#discussion_r701036958).

**Comment by wtrocki** [comment]
More info is needed for community to pick that up. (Where to change and what package to use)

**Comment by alexal** [comment]
@wtrocki I would like to work on this. Please assign this issue to me.

**Comment by wtrocki** [comment]
@alexal With broken heart I need to close that PR unmerged. We would need to introduce our own parsing format.
Apologies for not including this.
