### ISSUE TITLE
installed binary path is incorrect on RPM

### ISSUE THREAD

**Issue by beav** [redhat-developer/app-services-cli#1152]
## Description

**Version**: 0.31.1 

The RHOAS rpm will install the binary to `/usr/bin/bin/rhoas` which is not on the default path. I suspect it should be `/usr/bin/rhoas`.

### Steps to reproduce

1. Install rhoas 0.31.1 rpm
2. attempt to run "rhoas"
3. `rhoas: command not found`

### Expected vs actual behaviour

The rpm is installing the rhoas bin to `/usr/bin/bin/rhoas` instead of `/usr/bin/rhoas`. You can verify via `rpm -ql`:

```
$ rpm -ql rhoas
/usr/bin/bin/rhoas
```

**Comment by wtrocki** [comment]
Thank you for logging new issue
What would be your os/version?

I think we have this fixed recently but that fix might introduced another problem
https://github.com/redhat-developer/app-services-cli/pull/836

**Comment by alexal** [comment]
@wtrocki I've fixed the problem

**Comment by wtrocki** [comment]
@beav We hoping to schedule another release soon with fixed RPM. Thank you so much for reporting issue.

@alexal Thank you so much for your community contribution! really appreciate it.
