### ISSUE TITLE
Installer script uses outdated path for binary

### ISSUE THREAD

**Issue by SamBarker** [redhat-developer/app-services-cli#1157]
## Description
Installer uses outdated path for binary within the OS X tarball.
**Version**: 0.32.0

I've just tried to install 0.32.0 on MacOS. The script successfully downloaded the tar ball and uncompressed it however it then failed with 
```
Downloading rhoas v0.32.0
rhoas v0.32.0 downloaded
cp: rhoas_0.32.0_macOS_amd64/bin/rhoas: No such file or directory
```

It looks like https://github.com/redhat-developer/app-services-cli/pull/1153/ changed the output when building the tar ball, but the OS X install script still expects it to be in `bin`. You can see the distribution below.

```
tree rhoas_0.32.0_macOS_amd64
rhoas_0.32.0_macOS_amd64
├── CHANGELOG.md
├── LICENSE
├── README.md
└── rhoas
```

**Comment by alexal** [comment]
Fixed.
