### ISSUE TITLE
Client-side validation of the `service-account list` command output

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1159]
### Feature or problem description

The `ListServiceAccounts` endpoint does not offer pagination parameters so we are listing all data. It is likely that there would be multiple service accounts allowed per user, potentially leading to 100s or 1000s of items being printed. We need to offer pagination to make this list more easily read.

### Proposed solution

Add a `limit` and `offset` flag and do the pagination from the CLI.

**Comment by wtrocki** [comment]
To be clear. Proposal is to perform client side pagination or use backend - file new request (that should not be issue)?

**Comment by craicoverflow** [comment]
There were some technical reasons for not being able to do this on the backend, it was there but removed because it did not work correctly. @akoserwal do you know if this is possible yet?

**Comment by akoserwal** [comment]
Raised issue with Keycloak team: https://issues.redhat.com/browse/KEYCLOAK-17822

**Comment by craicoverflow** [comment]
Thanks for confirming this is still not technically possible. In that case I think we should do client-side pagination on this in the meantime.

**Comment by wtrocki** [comment]
Update. This is unlikely to be addressed in any time period due to backend not supporting it.

**Comment by wtrocki** [comment]
We need to push for better architecture on control plane to fix it
