### ISSUE TITLE
Add `--search` flag to `rhoas service-registry list`

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1165]
### Feature or problem description

`rhoas service-registry list` should allow user to filter list of service registries using `--search` flag.

### Proposed solution

Add a flag `--search` to `rhoas service-registry list`. It should have the description: `Text search to filter the Service Registry instances by name`.

**Comment by Jayita10** [comment]
Can I work on this issue?

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please tell the description to be added along <a href="https://github.com/redhat-developer/app-services-cli/blob/f9a8e845562c65f7bd13516649f7c40d582d3c7c/docs/commands/rhoas_service-registry_list.adoc#rhoas-service-registry-list">here</a> in <code>options</code>

**Comment by craicoverflow** [comment]
If you check out the `rhoas kafka list` command and keep a similar description, but adapted to service-registry.

**Comment by wtrocki** [comment]
Sadly this is not going to be possible - we have requirement for that in jira but it haven't been prioritized by BU to force us to have backend support
