### ISSUE TITLE
IsOrgAdmin is available on token claim

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1166]
We currently using https://github.com/redhat-developer/app-services-cli/blob/cluster-complete-mess/pkg/api/rbac/api.go#L31:L31 this to check if user is admin

**Comment by craicoverflow** [comment]
What is the action here? The issue is unclear to me. Where is that field being used exactly?

**Comment by wtrocki** [comment]
In not pushed code for ACL that you haven't seen :). Let's triage this on the next call.

**Comment by wtrocki** [comment]
Update. Decision was made to use RBAC API. Created issue to cover extra requirements.
https://issues.redhat.com/browse/RHCLOUD-16448
