### ISSUE TITLE
Use the pre-defined service status constant values

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1174]
In some places, unassigned strings are being used to refer to the various possible service status values. There are constants defined in the [`svcstatus`](https://github.com/redhat-developer/app-services-cli/blob/db1abd96389bad334014e3cce98f210e780ac1a1/pkg/connection/keycloak_connection.go#L254-L268)package for this which should be used.

Location 1:
https://github.com/redhat-developer/app-services-cli/blob/db1abd96389bad334014e3cce98f210e780ac1a1/pkg/connection/keycloak_connection.go#L216-L229

Location 2:
https://github.com/redhat-developer/app-services-cli/blob/db1abd96389bad334014e3cce98f210e780ac1a1/pkg/connection/keycloak_connection.go#L254-L268

**Comment by kashifsoofi** [comment]
Can I attempt this please?

**Comment by wtrocki** [comment]
@craicoverflow catching up with issues. 
Ideally we should use enums from individual sdks as we deal with separate backends, but proposed package is still much better than strings :)

**Comment by craicoverflow** [comment]
Yes, this package exists already though and is a quick-win. Long-term, I agree this should be in the SDK.

**Comment by wtrocki** [comment]
It is in SDK already - Every SDK has status enum

**Comment by craicoverflow** [comment]
Yes, for service registry but not for Kafka. Service registry has fewer enum values (it does not have `PROVISIONING`).

I recall an issue (https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/issues/386) about this but it was closed as this change would introduce backwards-incompatible changes to consuming clients..
