### ISSUE TITLE
Add convenience command to give a principal producer access to a certain topic

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1175]
### Feature or problem description

When I'm configuring my ACLs of my Kafka topic

I want to give a principal producer access to a certain topic in single command

So I don't have to set the 3 required ACLs to produce to a topic (WRITE, DESCRIBE, CREATE) individually.

The Kafka Bin Scripts have a convenience command to set the required allowed operations on the topic resource (WRITE, DESCRIBE, CREATE) if you want to allow a principal to produce to a topic. This allows users to do common tasks (allowing a principal to produce to a topic) in a single command, without the need for the user to have to know what operations need to be allowed on the resource.

### Proposed solution

```shell
$ rhoas kafka acl producer --user <principal-id> --topic-prefix rhoas
```

**Comment by rkpattnaik780** [comment]
Fixed by #1179
