### ISSUE TITLE
Debug mode for install.sh script

### ISSUE THREAD

**Issue by rkubis** [redhat-developer/app-services-cli#1189]
### Feature or problem description

When I tried to install `rhoas` CLI, I got error message: `Release tag latest not found`, but the issue was that I exceeded API rate limit of GitHub.

So, I got wrong error message in this case.

### Proposed solution

Ability to run installation script in debug mode, or proper error message when an issue happens during installation process.

### Additional context

I tried to install `rhoas` CLI on my Fedora 34 virtual machine inside OpenStack that has single IP for all VMs.

**Comment by craicoverflow** [comment]
Closing this as we will eventually migrate to productized CLI on devportal.
