### ISSUE TITLE
Credentials file path should be highlighted in a colour

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1194]
When running `rhoas service-account create` and `rhoas service-account reset-credentials`, we print the file path of the credentials when the operation has completed.
 
```shell
✔️ Credentials saved to /home/joebloggs/code/github.com/redhat-developer/app-services-cli/.env
```

The file path should be highlighted using `color.CodeSnippet(filePath)` to make it stand out.

**Comment by ananichev** [comment]
I'll take that one
