### ISSUE TITLE
`grant-permissions` should check if rules already exist

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1209]
### Feature or problem description

Creating the same rules twice prints success message

Originally discussed [here](https://github.com/redhat-developer/app-services-cli/pull/1179#issuecomment-940046836)

**Comment by rkpattnaik780** [comment]
While it is possible to check if a rule exists before every creation using filters, it might slow down commands that create multiple rules using synchronoyus API requests. My take would be to - close it or keep it blocked till API supports batch creation and lookup. Wdyt @craicoverflow @wtrocki ?

**Comment by craicoverflow** [comment]
I agree with you. Due to the idempotent nature of the command, nothing dangerous or unexpected can happen from running the command twice.

Another option: is there a different status code returned if an ACL already exists? If so, we could track the number of successful requests and diff it against the total number of requests.

**Comment by wtrocki** [comment]
I like us to bounce those ideas with Kafka sounding board to ask kafka experts what they would typically expect. I'm happy to facilitate them with their group

I'm in no means expert but it feels like this will be hard to do as grant access commands have non binary results so it will be hard to check if access is there without false positives.

**Comment by wtrocki** [comment]
Example. If first rule exist but others do not user experience is to delete it manually? Or cli delete it?

Sometimes easier solutions have better UX as users understand behaviour. Command creates set of acl always etc.

**Comment by craicoverflow** [comment]
> I'm in no means expert but it feels like this will be hard to do

Since a couple of approaches are mentioned in this issue, could you go into which option you think will be hard to do? Just so that there are no misunderstandings.

**Comment by rkpattnaik780** [comment]
> Another option: is there a different status code returned if an ACL already exists? If so, we could track the number of successful requests and diff it against the total number of requests.

Upon investigating, same status code is returned if the ACL already exists.

**Comment by wtrocki** [comment]
> Since a couple of approaches are mentioned in this issue, could you go into which option you think will be hard to do?

I really do not want to discuss any technical solutions without understanding if that requirement makes sense. Core issue here is that we seem to bring this new requirement in GitHub, so first for us would be to bring and validate that requirement with stakeholders etc.

**Comment by wtrocki** [comment]
Upon validation it looks like there is no duplicate ACLs possible so IMHO we should ask backend to implement ability to detect existing acl/return different code

**Comment by craicoverflow** [comment]
Yes, this is the approach suggested earlier. What has changed so that we should not bring this to the Kafka sounding board?
