### ISSUE TITLE
Error message should make it clear `--topic-prefix` or `--topic` can be used

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1224]
In the `kafka acl grant-access` command:

`--topic` OR `--topic-prefix` can be passed, but error messages do not make this known - they say "--topic" is required.

The error message must reflect the allowed values.

```shell
$ rhoas kafka acl grant-access --producer --user ephelan_kafka_devexp
❌ "--topic" flag is required for consumer and producer operations. Run the command in verbose mode using the -v flag to see more information
```

**Comment by gkpani97** [comment]
Hello @craicoverflow , I'm interested in solving this issue, can you assign it to me.
