### ISSUE TITLE
Group commands in the CLI reference guide

### ISSUE THREAD

**Issue by bhardesty** [redhat-developer/app-services-cli#1225]
### Feature or problem description

In the script that generates the rhoas CLI reference guide (https://github.com/redhat-developer/app-services-cli/blob/c5bd4c29308b159df6c60382005501714a61bd52/internal/docs/modular_docs.go), the commands are included into the ref guide in alphabetical order, without any categorization (https://github.com/redhat-developer/app-services-cli/blob/modular-docs/assemblies/assembly-cli-command-reference.adoc). This makes it difficult to navigate. 

### Proposed solution

Update modular_docs.go so that the assembly file that is created groups the CLI commands into sections.

I propose that we use the following categories (each category would be a separate section in the assembly file):
- Basic commands (all top-level rhoas commands that do not have any sub-commands)
- Cluster commands (all rhoas cluster * commands)
- Kafka commands (all rhoas kafka * commands)
- Service account commands (all rhoas service-account * commands)
- Service Registry commands (all rhoas service-registry * commands)

Within each category, include all of the commands within the applicable command family, in alphabetical order. (Note: we could further subcategorize the commands in the Kafka and Service Registry categories, but I found that this seems to result in too many subheading levels, and non-optimal formatting.)

To style this in the assembly file, each category name should be formatted like this:
```
[#category-name]
== Category name
```

Each command within the category should be included at `leveloffset=+2`.

For example, the service-account commands are currently included in the assembly file like this:
```
include::../modules/ref-cli-service-account-create.adoc[leveloffset=+1]
include::../modules/ref-cli-service-account-delete.adoc[leveloffset=+1]
include::../modules/ref-cli-service-account-describe.adoc[leveloffset=+1]
include::../modules/ref-cli-service-account-list.adoc[leveloffset=+1]
include::../modules/ref-cli-service-account-reset-credentials.adoc[leveloffset=+1]
include::../modules/ref-cli-service-account.adoc[leveloffset=+1]
```

When categorized in the "Service account commands" category, they should be included like this:
```
[#service-account-commands]
== Service account commands
include::../modules/ref-cli-service-account.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-create.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-delete.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-describe.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-list.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-reset-credentials.adoc[leveloffset=+2]
```
### Additional context

Here's a mockup of what the assembly file would look like if the above categorization is applied. Note that this uses a slightly older version of the CLI, so not every single rhoas command is represented in this example.
```
:context: rhoas-cli-command-reference
[id="cli-command-reference_{context}"]
= CLI command reference (rhoas)

[role="_abstract"]
You use the `rhoas` CLI to manage your application services from the command line.

[#basic-commands]
== Basic commands
include::../modules/ref-cli.adoc[leveloffset=+2]
include::../modules/ref-cli-completion.adoc[leveloffset=+2]
include::../modules/ref-cli-completion-bash.adoc[leveloffset=+2]
include::../modules/ref-cli-completion-fish.adoc[leveloffset=+2]
include::../modules/ref-cli-completion-zsh.adoc[leveloffset=+2]
include::../modules/ref-cli-login.adoc[leveloffset=+2]
include::../modules/ref-cli-logout.adoc[leveloffset=+2]
include::../modules/ref-cli-status.adoc[leveloffset=+2]
include::../modules/ref-cli-whoami.adoc[leveloffset=+2]

[#cluster-commands]
== Cluster commands
include::../modules/ref-cli-cluster.adoc[leveloffset=+2]
include::../modules/ref-cli-cluster-bind.adoc[leveloffset=+2]
include::../modules/ref-cli-cluster-connect.adoc[leveloffset=+2]
include::../modules/ref-cli-cluster-status.adoc[leveloffset=+2]

[#kafka-commands]
== Kafka commands
include::../modules/ref-cli-kafka.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-acl.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-acl-grant-permissions.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-acl-list.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-consumer-group.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-consumer-group-delete.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-consumer-group-describe.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-consumer-group-list.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-consumer-group-reset-offset.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-create.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-delete.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-describe.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-list.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-topic.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-topic-create.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-topic-delete.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-topic-describe.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-topic-list.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-topic-update.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-update.adoc[leveloffset=+2]
include::../modules/ref-cli-kafka-use.adoc[leveloffset=+2]

[#service-account-commands]
== Service account commands
include::../modules/ref-cli-service-account.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-create.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-delete.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-describe.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-list.adoc[leveloffset=+2]
include::../modules/ref-cli-service-account-reset-credentials.adoc[leveloffset=+2]

[#service-registry-commands]
== Service Registry commands
include::../modules/ref-cli-service-registry.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-create.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-delete.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-download.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-export.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-get.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-import.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-list.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-metadata-get.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-metadata-set.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-state-set.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-update.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-artifact-versions.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-create.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-delete.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-describe.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-list.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-role.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-role-add.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-role-list.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-role-revoke.adoc[leveloffset=+2]
include::../modules/ref-cli-service-registry-use.adoc[leveloffset=+2]
```

**Comment by wtrocki** [comment]
I think we can go with 2 options here:

Apply modifications for engine but that would be related to commands structure itself like append content to single file. Keep subcommands in subfolders etc. Drawback of that is that it will be really hard to adapt this downstream

Alternative would be to threat generated content as modules and create separate assembly object downstream. This would be much better option as it will allow us to apply layout as suggested in the issue. 
Drawback for that will be maintenance for the new commands.

We have 4 issues related to assembly of those + want to also publish our own upstream reference so lets sync later next week to see what will be the best option for your team

**Comment by smccarthy-ie** [comment]
@wtrocki @bhardesty Can this issue be prioritized? We've had feedback from new users about the CLI ref navigation, and with all the new RHOAS services coming onstream, this issue will only get worse. Thanks

**Comment by wtrocki** [comment]
Sure. I will do that now.
 Reason why we did not action it was lack of reply to the options. If you tell me what is the best way for you to go forward

**Comment by bhardesty** [comment]
@wtrocki I think there are several options. What do you think would be best?

Option 1: We generate the assembly file in the upstream similar to the proposed solution above. The downside is that if we ever need to adjust anything in the assembly file for downstream publishing, we'll have to update the doc generation engine to build the assembly file differently.

Option 2: We just generate each command as a separate adoc file. Downstream, we maintain the assembly file and include the individual command adoc files however we want. This makes it easy if we need to adjust the assembly file, but we wouldn't have a simple way to handle new and removed commands - we'd have to manually change the assembly file downstream every time a command is added or removed.

Option 3: Instead of an upstream assembly file, we generate some sort of data structure that defines the CLI structure (i.e. groups commands into families). Perhaps a JSON or YAML file. Then downstream, we maintain the assembly file and use the upstream data structure to "map" the CLI structure to the included commands.

**Comment by wtrocki** [comment]
Amazing feedback! Thank you so much. I done some code investigation and I feel that we can keep ascidocs specific to what dowstream wants as upstream will have markdown files anyway. mix of Option 3 and option 1 will land into PR

**Comment by bhardesty** [comment]
Thanks, @wtrocki! Once the PR is ready, I'll try to build the CLI ref guide downstream to verify.
