### ISSUE TITLE
Add more details to the `kafka acl list` help output

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1227]
Feedback:

> I find the `kafka acl list` output hard to grasp as a non ACL expert. Maybe it’s fine but I’m not 100% clear what it tells me with regards to who has access to what.
> Maybe exploring with explicit “connection words: principal is permissioned to do operation

See https://github.com/redhat-developer/app-services-cli/issues/1227#issuecomment-951064119 on what we should do.

**Comment by wtrocki** [comment]
I like us to follow KISS. google mantra to avoid flags and unneeded complexity. My take is that UI does present the same data like we do so this feedback is more to ux team.

I think acls we display are clear and less risky for confusion/missinterpretation
