### ISSUE TITLE
Smarter error handling in ACL commands

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1229]
This feedback can also be generally applied and is not exclusive to ACL, but these commands have a lot of possibly input combinations and so the need for more sympathetic error messages is more apparent.

Look at the following journey a user might take if they do not look the command documentation using `--help` (which is very likely).

```shell
 ╱  ~/code  rhoas kafka acl grant-access                                                                                                                                   INT ✘ ╱ 15:39:55 
❌ No operation specified: must provide atleast one of "--producer" or "--consumer" flag. Run the command in verbose mode using the -v flag to see more information


  ╱  ~/code  rhoas kafka acl grant-access -v                                                                                                                                  1 ✘ ╱ 15:40:04 
❌ No operation specified: must provide atleast one of "--producer" or "--consumer" flag. Run the command in verbose mode using the -v flag to see more information


  ╱  ~/code  rhoas kafka acl grant-access --producer                                                                                                                          1 ✘ ╱ 15:40:08 
❌ Principal is missing, provide "--user" or "--service-account" flag. Run the command in verbose mode using the -v flag to see more information


  ╱  ~/code  rhoas kafka acl grant-access --producer -v                                                                                                                       1 ✘ ╱ 15:40:15 
❌ Principal is missing, provide "--user" or "--service-account" flag. Run the command in verbose mode using the -v flag to see more information


  ╱  ~/code  rhoas kafka acl grant-access --producer --service-account srvc-acct-blah-blah-blah                                                        1 ✘ ╱ 15:40:18 
❌ "--topic" flag is required for consumer and producer operations. Run the command in verbose mode using the -v flag to see more information


  ╱  ~/code  rhoas kafka acl grant-access --producer --service-account srvc-acct-blah-blah-blah--topic movies                                          1 ✘ ╱ 15:40:43 
The following ACL rules are to be created:

  PRINCIPAL (5)                                    PERMISSION         DESCRIPTION
 ------------------------------------------------ ------------------ -------------------------
  srvc-acct-blah-blah-blah  ALLOW | DESCRIBE   TOPIC is "movies"
  srvc-acct-blah-blah-blah  ALLOW | WRITE      TOPIC is "movies"
  srvc-acct-blah-blah-blah  ALLOW | CREATE     TOPIC is "movies"
  srvc-acct-blah-blah-blah  ALLOW | WRITE      TRANSACTIONAL_ID is "*"
  srvc-acct-blah-blah-blah  ALLOW | DESCRIBE   TRANSACTIONAL_ID is "*"

? Are you sure you want to create the listed ACL rules Yes
✔️ ACLs successfully created in the Kafka instance "my-kool-kafka"
```

We are "drip-feeding" the information required to fully execute the command. By throwing an error on the first encountered missing value, we are not collecting the other missing values.

It would be better to go through the remaining inputs, and collect other missing or invalid values, and include them into one error. 

This will reduce the number of times the user runs this command from 6 to 2.

**Comment by rkpattnaik780** [comment]
Looking for some feedback @craicoverflow @wtrocki . Does the following qualify as to how we should be displaying the flag errors?

![Screenshot from 2021-11-22 16-50-30](https://user-images.githubusercontent.com/23582438/142853152-7c9b0bbc-afe8-4380-8551-df22c909f243.png)

**Comment by wtrocki** [comment]
Do you mean if we should use "--topic" vs "topic flag" ?

**Comment by craicoverflow** [comment]
> Do you mean if we should use "--topic" vs "topic flag" ?

No. It is about aggegrating all errors into one instead of "drip-feeding". The issue description should provide more context.

**Comment by craicoverflow** [comment]
> Looking for some feedback @craicoverflow @wtrocki . Does the following qualify as to how we should be displaying the flag errors?

Yes @rkpattnaik780 that is more or less how it should be. The error should be formatted more though just to make it more readable (some indentations or maybe bullet-points)..see what looks best.
