### ISSUE TITLE
Improve logging of service account credentials generated via `cluster connect`

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1242]
## Description

**Version**: 0.34.2

Currently the CLI prints the client ID of generated service account to the terminal.
Investigate if the credentials could be stored in a file or some better approach for logging it.

**Comment by craicoverflow** [comment]
Is there a way in which it would make sense to attach the client ID to the KafkaConnection CR?

**Comment by craicoverflow** [comment]
It may not be indeed, but I do think we need to make the client ID retrievable in some way at a later point in time, or have the user save it to a file during `cluster connect`.
