### ISSUE TITLE
Kafka ACL table should print the mapped values instead of directly printing the enums from the backend

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1247]
For the ACL CRUD commands we have mapped all enums from permission, operation, resource type to lower case forms. There are a couple of reasons making the user enter uppercase values is not preferred and we should try to avoid this:

- It is more difficult to type, as the user must turn on CAPS LOCK.
- It is more difficult to read, as uppercase letters are more uniform and harder to tell apart.

Current output:

```shell
  PRINCIPAL (6)    PERMISSION   OPERATION          DESCRIPTION                 
 ---------------- ------------ ------------------ ---------------------------- 
  All accounts     ALLOW        DESCRIBE_CONFIGS   TOPIC is "*"                
  All accounts     ALLOW        DESCRIBE           TOPIC is "*"               
```

Preferred output:

```shell
  PRINCIPAL (6)    PERMISSION   OPERATION          DESCRIPTION                 
 ---------------- ------------ ------------------ ---------------------------- 
  All accounts     allow        describe-configs   topic is "*"                
  All accounts     allow        describe           topic is "*"               
```

**Comment by craicoverflow** [comment]
Taking this one now.

**Comment by wtrocki** [comment]
Should this wait for release?

**Comment by craicoverflow** [comment]
No, it's fine, there are several places that need to be updated for this.
