### ISSUE TITLE
Remove acl list operation to preview ACLs to be deleted

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1250]
## Description

**Version**: 0.34.2

`kafka acl delete` makes an acl list query to get a preview of the ACL rules to be deleted. This causes an issue whenever the specific rule is defined for `all accounts` as well.

Orginally discussed [here](https://github.com/redhat-developer/app-services-cli/pull/1218#issuecomment-948351867)

### Steps to reproduce

1. Create same ACLs for user "abc" and all accounts using UI.
2. Deleting the ACL for user "abc" via `kafka acl delete` command will remove both the rules(for user abc and all accounts)

### Expected
`acl delete` should delete the rule for specified user leaving the rule for all accounts as it is.

**Comment by craicoverflow** [comment]
No, I'm not necessarily looking to, I just wanted to avoid any assumptions. Could you assign this to yourself if you plan on checking it out? I think it's important to do soon.
