### ISSUE TITLE
Client side validation for service-account inputs for ACL commands

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1260]
Multiple ACL commands use `--service-account` flag. DEscription might not always be enough to prevent user from providing `client ID` instead of `service-account id`. Some client side side validation would be useful to let the user know the difference between service account ID and client ID.

Originally raised by @wtrocki

**Comment by craicoverflow** [comment]
We could do fully client-side validation as it will be months before the service account API will be ready. Validation is very important so if we can do _any_ we should.

**Comment by rkpattnaik780** [comment]
> We could do fully client-side validation as it will be months before the service account API will be ready. Validation is very important so if we can do _any_ we should.

We should put a regexp for client id validation for now I guess.

**Comment by wtrocki** [comment]
I think we should contribute that endpoint to backend. 
Done investigation and it happen to be trivial due to ability to provide search attribute containing clientId

https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/0eade24f6d5056faeed5835106bbd8c1ba5266a5/pkg/services/keycloak.go#L320

I'm was on lookout for someone who would do it but we can do it ourselves.

**Comment by craicoverflow** [comment]
What I mean is we can:

1. Pull ALL service accounts from the backend
2. Cache them and check locally if they exist.

> I think we should contribute that endpoint to backend.

We had a call with the fleet manager team last week where we agreed that this is something that should wait as any change made in the kas-fleet-manager would also need to be applied to the new service account CIAM API. Any contributions there would need to be synchronized/approved by them.

**Comment by wtrocki** [comment]
I had 2 calls after that :) and action for next week to discuss with PM and do it in our team.
No one will do it unless:

- We raise this with PM 
- We do it ourselves

So we agreed that their team doest want to do it.
Lack of this endpoint is really bad experience.
Users cannot effectively reset their service account knowing only clientId etc. Validate user input.

I recomend to not do any client side validation for now as it will be more effort and not solving this problem

**Comment by craicoverflow** [comment]
Fair enough. I recommended client-side validation on the presumption that it would not be possible short-term on the backend.

**Comment by wtrocki** [comment]
We should have now epic for that work. Closing
