### ISSUE TITLE
Lack of support for ARM M1 binaries (new apple laptops)

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1272]
## Description

Lack of support for ARM M1 binaries (new apple laptops).
We need  to add goreleaser support for this type of binary and test it

**Comment by wtrocki** [comment]
@craicoverflow do you have  Apple laptop with M1 chip for testing binary?

**Comment by craicoverflow** [comment]
I do not.

**Comment by craicoverflow** [comment]
Was this resolved?

**Comment by wtrocki** [comment]
Yes. https://github.com/redhat-developer/app-services-cli/releases/tag/v0.36.0-beta2
