### ISSUE TITLE
kafka create doesn't handle regions properly

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1277]
## Description

We fetch regions from API only in the interactive mode. 
We do not have validation for provider or region or provide shell extension for those values.

**Comment by craicoverflow** [comment]
The reason for this is that the region will depend on the cloud provider. AWS may have eu-west-1 but may not have eu-west-2, which Google Cloud has. With flags, you have not selected a cloud provider, so a region will not be loaded.

Let's leave this open though, to see if there is anything we can do.

**Comment by wtrocki** [comment]
Yes. We should validate cloud provider and region together

**Comment by craicoverflow** [comment]
Can you elaborate?

**Comment by wtrocki** [comment]
We do not provide validation for cloud and region. User can provide any value

**Comment by craicoverflow** [comment]
Thank you.
