### ISSUE TITLE
rhoas kafka acl delete is not functional

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1278]
## Description

Delete command doesn't seem to recognize existing ACL rules. 
Trying to deleting ACL rule according to the spec returns zero matches.

**Comment by wtrocki** [comment]
Reported today. I think @craicoverflow is working on improving delete as we have done it with some asumptions/decisions that might not be valid/problematic.

**Comment by craicoverflow** [comment]
@wtrocki what would help me a lot is an example of the command that was executed, what happened versus what was expected.

**Comment by craicoverflow** [comment]
Should this be closed?

**Comment by wtrocki** [comment]
Still testing but issue is vague so will close it and create proper issue once there
