### ISSUE TITLE
Service account describe by ID

### ISSUE THREAD

**Issue by fvaleri** [redhat-developer/app-services-cli#1279]
`service-account describe` works by ID, but I know the SA name when creating a new one, and this is what I would like use to get the corresponding ID, without having to grep the `service-account list` first.

**Comment by craicoverflow** [comment]
Thank you @fvaleri for raising this. We are actively working with the backend teams to support this, #1260 is also blocked by this.

**Comment by fvaleri** [comment]
Ok, thanks for the feedback @craicoverflow.

**Comment by craicoverflow** [comment]
This is now being tracked in JIRA and will be done.
