### ISSUE TITLE
Create does not handle well "all" as alias creating topic with all

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1282]
## Description

```
[wtrocki@graphapi app-services-cli (main)]$ rhoas kafka acl create --operation alter --permission deny --user wtrocki@redhat.com --topic all
debugEnabled false
The following ACL rules are to be created:

  PRINCIPAL            PERMISSION   OPERATION   DESCRIPTION     
 -------------------- ------------ ----------- ---------------- 
  wtrocki@redhat.com   DENY         ALTER       TOPIC is "all"  
  
```

Expected

[wtrocki@graphapi app-services-cli (main)]$ rhoas kafka acl create --operation alter --permission deny --user wtrocki@redhat.com --topic all
debugEnabled false
The following ACL rules are to be created:

  PRINCIPAL            PERMISSION   OPERATION   DESCRIPTION     
 -------------------- ------------ ----------- ---------------- 
  wtrocki@redhat.com   DENY         ALTER       TOPIC is "*"

**Comment by craicoverflow** [comment]
I think you have fixed this now @wtrocki
