### ISSUE TITLE
Provide dynamic configuration that CLI downloads on login

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1288]
### Definition of the problem

Users downloading CLI sporadically and might not update it often. 
We need ability for CLI to turn on/off certain features after CLI is released to not force users to update every time we introduce some breaking change.

## Examples

We need to be able to turn off mas-sso when it is migrated. Migration will be instantaneous - meaning we would not have period of 2 SSO running and supported at the same time.

## Configuration options

MasSSO Enabled - Controls if CLI SHOULD login to mas-sso and uset it's tokens
Telemetry Enabled - Controls if telemetry is enabled for production users
TermsAndConditions metadata.

**Comment by craicoverflow** [comment]
Title needs to be clarified.

**Comment by wtrocki** [comment]
@craicoverflow would you have time to work on this for context of dynamic disabling of mas-sso

**Comment by craicoverflow** [comment]
Yep.

**Comment by craicoverflow** [comment]
Change priority from `critical` to `important-soon`.

**Comment by wtrocki** [comment]
That is fair. I will assign that to me to formulate plan and get details.

**Comment by wtrocki** [comment]
Some concerns were raised about that. Closing for now and will consider epic if needed
