### ISSUE TITLE
Add ability to bypass terms and conditions check when creating a Kafka or service registry instance

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1294]
## Problem

It would be useful if the kas-installer could just use the rhoas cli, that would allow several of the scripts that currently > support the kas-installer to be removed and drive all our use-cases towards one set of tooling.

One barrier is the T&C check made by the CLI. When you run kas from the kas-installer, fleet-manager is configured not to enforce a T&C check, but the CLI doesn't know that. The T&C check made by the CLI fails because the T&C endpoint doesn't exist.

> redhat-developer/app-services-cli@441f55f/pkg/cmd/kafka/create/create.go#L144

## Solution
One simple solution might be a flag in the CLI (environment variable or command line switch) that allowed the check to be bypassed. If it were to exist, there'd be no chance that a user could use this to bypass T&Cs in real life as the fleet-manager normally enforces this on creation.

**Comment by craicoverflow** [comment]
My preference for this would be to use a flag which is hidden from completions and documentation.

We can hide a flag in Cobra easily:
```shell
// Hide flag for this command
command.Flags().MarkHidden("some-flag")
```

A benefit of a flag is we can direct users to try this option of the terms and conditions pre-check is causing issues.

**Comment by wtrocki** [comment]
+1 for CLI flag
