### ISSUE TITLE
Lag/Anomaly in synchronous in Kafka creation

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1301]
## Description

**Version**: 0.36.2

Yesterday while creating a Kafka instance in synchronous mode, it took unusually long time. Checking with `kafka list` and `kafka describe` showed it to be ready.

![Screenshot from 2021-11-08 20-41-59](https://user-images.githubusercontent.com/23582438/140877404-ed1879c0-a405-4667-807c-059dd77a0811.png)

### Steps to reproduce

This issue might be encountered sporadically.

**Comment by craicoverflow** [comment]
> Version: 0.36.2

Have you experienced this on the released CLI, or just with the dev (local) version?

**Comment by rkpattnaik780** [comment]
> > Version: 0.36.2
> 
> Have you experienced this on the released CLI, or just with the dev (local) version?

Both

**Comment by wtrocki** [comment]
@rkpattnaik780 Can you confirm if that is still happening?

**Comment by rkpattnaik780** [comment]
It is still happening for me.

**Comment by craicoverflow** [comment]
Have you been able to see it in verbose mode to monitor network requests?

**Comment by rkpattnaik780** [comment]
Unfortunately no, but I think one possibility for this to be happening would be the intermittent `dial tcp i/o timeout error`

**Comment by craicoverflow** [comment]
So it could be a network issue on your side?

**Comment by wtrocki** [comment]
I have tested that now using network conditioner and it seems to be working fine even with 3g networks. 
It does actually exit when connection is too slow: https://github.com/redhat-developer/app-services-cli/blob/main/pkg/cmd/kafka/create/create.go#L251-L253 

Let's leave it open. I was asking in hope that we can close that as intermittent issue but it looks like it would not be easy to find/solve

**Comment by rkpattnaik780** [comment]
> So it could be a network issue on your side?

Tried creating artificial conditions during creation, it stops rather than continuing with the last status.

**Comment by wtrocki** [comment]
Lets agree to reopen it when it happens again
