### ISSUE TITLE
Broken update summary for Kafka update operation

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1302]
## Description

Update summary while doing owner update seems to be broken.

**Version**: 0.36.2

![Screenshot from 2021-11-09 13-35-36](https://user-images.githubusercontent.com/23582438/140886613-c5c84508-69d3-4bfd-a2a3-50189a0192c0.png)

### Steps to reproduce

Change owner for a given kafka instance
```
rhoas kafka update --owner=foo_user
```
It should display the update summary.

**Comment by craicoverflow** [comment]
That is likely caused by the SDK changes in https://github.com/redhat-developer/app-services-cli/pull/1297

**Comment by rkpattnaik780** [comment]
Do we need to add an additional flag for [reauthentication_enabled](https://github.com/redhat-developer/app-services-sdk-go/blob/b336464c92c51db788c609fc53073bf07082b91a/.openapi/kas-fleet-manager.yaml#L1201) too?

**Comment by craicoverflow** [comment]
No, not yet anyway. Product management will produce some epics and we can add it then.

**Comment by wtrocki** [comment]
No need.
I would discuss that with PM.

**Comment by wtrocki** [comment]
We have separate epic to cover  reauthentication_enabled that is not yed prioritised. We can ignore that for now
