### ISSUE TITLE
Remove reflect from kafka update preview

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1316]
## Description

The kafka update preview currently uses reflect package to parse data dynamically from `updateObj` struct. It depends largely on the SDK typings which can introduce breaking changes that could go undetected with the dynamic approach.

It can be simplified by operating directly on the SDK model properties.

Originally raised [here](https://github.com/redhat-developer/app-services-cli/pull/1311#discussion_r747615187).

**Comment by wtrocki** [comment]
Do you want me to see if backend can fix it?

**Comment by craicoverflow** [comment]
This is not something the backend can fix.

**Comment by wtrocki** [comment]
Ok. I got impression that defining objectbin openaoi will fix it
