### ISSUE TITLE
Wrong help test for `--output` in `service-registry artifact create`

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1318]
## Description

**Version**: 0.36.3

The `--output` flag for `service-registry artifact create` has description - Format in which to display the Service Registry instance.
It should be changed to : `Format in which to display the artifact`

![Screenshot from 2021-11-16 00-43-01](https://user-images.githubusercontent.com/23582438/141949703-7dc1ef8e-7bfb-4335-b5e2-424f9ac2c4aa.png)

### Steps to reproduce

1. Run `rhoas service-registry artifact create -h`

**Comment by craicoverflow** [comment]
We should use the common flag set for all `output` and `yes` flags:

https://github.com/redhat-developer/app-services-cli/blob/060f870988c2bc77fabc4ea1d3e9c5a95d2b7fce/pkg/cmdutil/flagutil/flagset.go#L35-L66

The approach can be pretty much cloned from here: https://github.com/redhat-developer/app-services-cli/blob/e56d44356618fab98b3db1c8c76b22d58232798e/pkg/cmd/kafka/topic/create/create.go#L130-L131

While these common flags become less unique in their individual descriptions, it should be much more sustainable.

**Comment by rkpattnaik780** [comment]
> We should use the common flag set for all `output` and `yes` flags:

Would you like to create a separate issue for this task?
