### ISSUE TITLE
Use the common flag set across all commands

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1320]
We should use the common flag set in all commands which still directly use `cmd.Flags()` directly.

https://github.com/redhat-developer/app-services-cli/blob/060f870988c2bc77fabc4ea1d3e9c5a95d2b7fce/pkg/cmdutil/flagutil/flagset.go#L35-L66

The approach can be pretty much cloned from here: https://github.com/redhat-developer/app-services-cli/blob/e56d44356618fab98b3db1c8c76b22d58232798e/pkg/cmd/kafka/topic/create/create.go#L130-L131

While these common flags become less unique in their individual descriptions, it should be much more sustainable.

_Originally posted by @craicoverflow in https://github.com/redhat-developer/app-services-cli/issues/1318#issuecomment-970053842_

**Comment by wtrocki** [comment]
Agree. Although I would connect this work with some form of mini SDK for creating RHOAS CLI rather than issue on it's own

**Comment by craicoverflow** [comment]
https://github.com/redhat-developer/app-services-cli/issues/965 has been open a while now to track refactoring the CLI public API. Since we don't have any short term plaans for a mini-SDK, I'd prefer to keep it disconnected for now, it can be tackled before then.

**Comment by craicoverflow** [comment]
This should be covered eventually by the SDK refactoring. Closing.
