### ISSUE TITLE
Creating a new artifact should return the URL to it

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1321]
### Feature or problem description

When creating an artifact in Schema Registry in CLI, it should print the URL to UI to view the newly created artifact.

### Proposed solution

The artifact url in the ui looks something like this - `https://console.redhat.com/beta/application-services/service-registry/t/d5e6012f-ce90-4aaf-85b3-5f6e21a97e60/artifacts/default/rama-5/versions/latest`

URL format: `<registry-browser-url>/artifacts/<group>/<id>/versions/<version>`

**Comment by rkpattnaik780** [comment]
@wtrocki would we like something similar for get metdata command?

**Comment by wtrocki** [comment]
Sure.
