### ISSUE TITLE
Print URL to view artifact in browser while getting the metadata 

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1323]
### Feature or problem description

`rhoas service-registry artifact metadata-get` should print the URL to UI to view the artifact as well.

### Proposed solution

The artifact url in the ui looks something like this - `https://console.redhat.com/beta/application-services/service-registry/t/d5e6012f-ce90-4aaf-85b3-5f6e21a97e60/artifacts/default/rama-5/versions/latest`

URL format: `<registry-browser-url>/artifacts/<group>/<id>/versions/<version>`

Similar to #1321

**Comment by craicoverflow** [comment]
Would it be a good idea to add it as an option in `--output=web` which would automatically open it in the browser?

**Comment by rkpattnaik780** [comment]
I was thinking of `--web` flag to open in browser maybe? We can discuss it with team.

**Comment by craicoverflow** [comment]
If we had `--json` and `--yaml` then yes I would agree - but we have already aligned to the standard of `--output` to determine how it should be displayed. Sure, we can discuss before making any move.

Relates to #317
