### ISSUE TITLE
Removing `href` field from the JSON returned for a Kafka instance

### ISSUE THREAD

**Issue by ppatierno** [redhat-developer/app-services-cli#1387]
The `create` and `describe` commands when handling a Kafka instance return a JSON containing multiple useful information for the user.
The one I am not sure is really useful for the user is the `href` link which refers to the REST endpoint for handling that specific Kafka instance and that is actually used internally by the rhoas cli (so doing HTTP calls to that REST endpoint).

```json
"href": "/api/kafkas_mgmt/v1/kafkas/c7i8c2uajn2pjibdblhg"
```

Is it really useful to return to the user? What a user could do knowing that REST endpoint? I don't see any usage for that or am I missing any obvious reasons?

**Comment by wtrocki** [comment]
Good idea!

For contributors
I feel like this would be SDK and control plane issue. We can flag in openapi fields in control plane that are internal as our clients return what backend returns. Then SDK will not include them

**Comment by wtrocki** [comment]
Update. I have discussed some options on backend and sdks.
The way we could do it is to have clone of sdk structures in cli that would mean significant work and problems with discovering new fields.

Href cannot be removed from api and for cli easiest way is to show what api shows
