### ISSUE TITLE
Retention bytes `-1` default value could not be clear to the user

### ISSUE THREAD

**Issue by ppatierno** [redhat-developer/app-services-cli#1395]
When handling topics on a Kafka instance, the retention bytes option help is printed as following.

```shell
--retention-bytes int     The maximum total size of a partition log segments before old log segments are deleted to free up space (default -1)
```

The description is clear but people could not understand what negative value as `-1` could mean as default unless reading the Kafka documentation which explains that it means "no limit in size".
Not sure if this is the way to go for a user or we should try to explain better.
Anyway, taking a look at flags go package I didn't find a way to add a kind of description to the default, so not sure if we have a better way to make it clearer.

**Comment by rkpattnaik780** [comment]
Since the -1 comes from the supplied default value, I think the only way to explain what it is will be to add an extra line in the description - "By default, no retention size limit is applied", or something similar.

**Comment by ppatierno** [comment]
I think it's the only way because AFAIK there is no way to add a text to describe the default value through flags package.

**Comment by wtrocki** [comment]
```
rhoas kafka topic create --retention-bytes
```

command needs better description for -1 flag as suggested by @rkpattnaik780
