### ISSUE TITLE
"$ rhoas cluster connect" command gives wrong output

### ISSUE THREAD

**Issue by fbm3307** [redhat-developer/app-services-cli#1422]
When we try to connect to the Kafka Cluster using the RHOAS CLI with command "$ rhoas cluster connect" , it doesn't give the available options to connect to the available instances, instead shows the details of the previous connection giving a result as the kafka with <previous instance id> instance id not present .

fmehta@fmehta-mac ~ % rhoas cluster connect
? Select type of service kafka
❌ Kafka instance with ID "c7el8l6l6br17rj1aro0" not found. Run the command in verbose mode using the -v flag to see more information

Here "Kafka instance with ID "c7el8l6l6br17rj1aro0"  was my previous kafka instance i had created in openshift hybrid cloud console and connected to, but after 48 hrs the instance will be deleted. Hence i created a new one and tried to connect to it, but it gives me this error.

Can this command either give a proper message incase the previous kafka instance would have been deleted or can the previous connection details be removed if the kafka instance is not available. In any case, can it always display options of available instances, i would like to connect to.? Can it allow to connect to multiple instances.?

**Comment by wtrocki** [comment]
> Here "Kafka instance with ID "c7el8l6l6br17rj1aro0" was my previous kafka instance i had created in openshift hybrid cloud console and connected to, but after 48 hrs the instance will be deleted. Hence i created a new one and tried to connect to it, but it gives me this error.

@fbm3307 did that kafka was created in UI or CLI. Creating kafka in the UI requires user to manually run 

`rhoas kafka use` command. 

> Can this command either give a proper message incase the previous kafka instance would have been deleted or can the previous connection details be removed if the kafka instance is not available

Yes! We are fixing that right now

**Comment by fbm3307** [comment]
@wtrocki Kafka was created using ui/console. But i always created the kafka using UI. The first time i created i wasn't required to use the **_"rhoas kafka use"_** command. Any reason why i wasn't required to do so.?

**Comment by wtrocki** [comment]
Oh. Now I know the whole story.
Amazing feedback! Thank you so much.

First time cluster connect ask to select kafka.
Second time assumed first kafka was used and printed error.

**Comment by wtrocki** [comment]
we know what caused the issue, and going to fix it but I have unassigned myself as fix will come with the feature branch and it might take a while to get that into released version of the CLI.

**Comment by wtrocki** [comment]
We have fixed that problem with new version of the context
