### ISSUE TITLE
tar: rhoas_0.38.5_linux_amd64.tar.gz: Cannot open: No such file or directory

### ISSUE THREAD

**Issue by kdubois** [redhat-developer/app-services-cli#1442]
## Description

**Version**: 0.38.5

I tried to run the following command (per the instructions this is how I should download the binary):
"curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh | bash "  
but it looks like the install script is pointing to a url that does not exist. 

Further examining the issue, it seems like the script is looking for a browser.download_url.* match in the following file, but I don't see any matches in that file: https://api.github.com/repos/redhat-developer/app-services-cli/releases/latest

### Steps to reproduce

just run 
"curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh | bash "  
on a Linux 64 machine (Fedora 34 in my case)

### Expected vs actual behaviour

I expected the binary to be downloaded :)

### Logs

Downloading rhoas v0.38.5
Error downloading rhoas 0.38.5
tar: rhoas_0.38.5_linux_amd64.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

**Comment by rkpattnaik780** [comment]
Thank you for reporting this @kdubois . This will be fixed asap in the next release.

**Comment by rkpattnaik780** [comment]
`rhoas v0.38.5` has been re-released. Can you try re-installing it with the following command:
```
curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh | bash
```

**Comment by kdubois** [comment]
perfect, now it works!
