### ISSUE TITLE
Non admin users should be able to update `reauthentication_enabled` field for Kafka instance

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1488]
## Description

Non-admin user should be able to update the value of `reauthentication_enabled` for the Kafka instance.
Current implementation allows only org admins to perform any kind of update operation for Kafka instances.

**Version**: 0.39.0

### Steps to reproduce

1. Try to update your Kafka instance using a non-admin account.
```
> rhoas kafka update --reauthentication true
Only organization administrators have the ability to update a Kafka instance.
```

**Comment by jackdelahunt** [comment]
Just need to verify this is still an issue

**Comment by rkpattnaik780** [comment]
Closing, the user can update now.
