### ISSUE TITLE
Fix Documentation about disable telemetry in USAGE_DATA.md

### ISSUE THREAD

**Issue by emanuelb** [redhat-developer/app-services-cli#1510]
## Description

in:
https://github.com/redhat-developer/app-services-cli/blob/c97509d53e76db1f4532ea4f25e7b8f9bd3bbcb3/USAGE_DATA.md#L12-L17
it show disable by `RHOAS_TELEMETRY=true` while in:

https://github.com/redhat-developer/app-services-cli/blob/16e2ed345ef5a8e0183f5e7a3bf15723d7ccf39d/pkg/core/localize/locales/en/common.en.toml#L19
it explain disable by `RHOAS_TELEMETRY=false`

from the code the correct value is `false`:
https://github.com/redhat-developer/app-services-cli/blob/04c5044f0b8a92c99e90ae6139492d273b083859/internal/telemetry/telemetry.go#L49

This was found while adding issue for this telemetry to toptout project: https://github.com/beatcracker/toptout

**Comment by wtrocki** [comment]
Amazing catch. Thank you for reporting. Fixing it
