### ISSUE TITLE
Fix lint issues with go v1.18

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1529]
### Feature or problem description

Upgrading go version to 1.18 in local throws multiple lint errors that didn't exist before.

The errors should be addressed before migrating to 1.18 in upstream.

**Comment by wtrocki** [comment]
See reply in https://github.com/redhat-developer/app-services-cli/issues/1530

I think both issues might be strongly correlated and should be done together

**Comment by rkpattnaik780** [comment]
Fixed in #1706
