### ISSUE TITLE
Remove http response bodies where not required

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1530]
## Description

Some commands while making api request use the `http.Response` object even if it is not required. This increases the lines of code and might result in unseen lint errors.

**Comment by wtrocki** [comment]
After quick research it looks like from 1.18.0 linting capabilities are much better - they can detect return types from underlying classes. This means that to enable 1.18.0 we can:

1. Disable that specific rule across CLI and remove any defer statements
2. Add defer body.close everywhere even if it is pointless

Option 1 seems much desired.

**Comment by rkpattnaik780** [comment]
Will vote for 1 too.

**Comment by jackdelahunt** [comment]
Fixed
