### ISSUE TITLE
mention the rhoas cli docker/container image in the README

### ISSUE THREAD

**Issue by machi1990** [redhat-developer/app-services-cli#1546]
### Feature or problem description

Requesting an image release of the rhoas cli

### Proposed solution

Users who want to quickly try things will just run the CLI via container 

### Additional context

Not sure how this will work with the login command etc

**Comment by wtrocki** [comment]
That is there since beginning and our guides use that image:
https://github.com/redhat-developer/app-services-tools

**Comment by machi1990** [comment]
Ah thanks. I was looking for this and I couldn't find. I'll close the issue then.

**Comment by wtrocki** [comment]
That is actually an issue. We need to document it in the readme
