### ISSUE TITLE
Display release notes in CLI

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1583]
Should the CLI have a way of displaying the release notes?

* There are certain CLIs that have additional command to print the release notes.
* Else we can log the release notes to terminal during an auto-updation. (like `omz`)

**Comment by wtrocki** [comment]
We had that enabled for autoupdates before but I have removed it as our release notes are very brief and in UI/Console form they are even less useful. 

My take is that we need "WhatIsNew.md" file in repo that can be seeded into Website and automated into each release. Release will carry this information + users can look into repo and website + we can include that into our reference guide. 

We could add command to include that file as well (at time of compilation) as another way to see things. This looks like easy win so we can start with getting this file created and maybe retrofit some of the recent updates?

**Comment by rkpattnaik780** [comment]
`WhatsNew.md` sounds good. We can get started on this.

**Comment by wtrocki** [comment]
@rkpattnaik780 Let's propose some format for what's new. The faster we get document the more content we will get there. 

I think we need:

- WhatsNew.md
- New chapter to contributing.md file

**Comment by rkpattnaik780** [comment]
How would this format look?


## 0.43.0

25 May 2022

Add optional text/description.

## What's new?

* feat(consumer-group): display state of consumer groups

## Fixed issues?

* fix: update kafka mgmt sdk for the latest version
* fix: add support for dynamic config url

**Comment by wtrocki** [comment]
This is changelog. What is new is typically more readable :)
Example
https://blog.ninja-squad.com/2021/12/10/angular-cli-13.1/
