### ISSUE TITLE
Add instructions for command completions for powershell

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1595]
### Feature or problem description

The `rhoas completion` command has instructions to enable command completions for zsh, bash and fish. We should allow users to have completions for powershell as well.

**Comment by wtrocki** [comment]
We need to update cobra. Powershell extensions are there to be copied:

https://github.com/spf13/cobra/blob/87ea1807f71dfa4d0bd7058c099b3978b128aea6/shell_completions.md
