### ISSUE TITLE
Unable to create service registry artifact 

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1685]
## Description

**Version**: 0.46.2 

### Steps to reproduce

Run the following command to create an artifact in your registry:

```
rhoas service-registry artifact create --artifact-id tweets-topic-2 --file "https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/docs/resources/avro-userInfo.json"
```

This fails with error message:
```
❌ Invalid body type application/create.extended+json
```

The command works fine for version `0.46.1`.

**Comment by wtrocki** [comment]
FYI @SafarMirek

**Comment by wtrocki** [comment]
Problem: https://github.com/redhat-developer/app-services-sdk-go/pull/544
