### ISSUE TITLE
Offline token login doesn't work for kafka subcommands

### ISSUE THREAD

**Issue by joselsegura** [redhat-developer/app-services-cli#1707]
## Description

**Version**: 0.48.0

When logged in console.redhat.com using `rhoas login --token $OFFLINE_TOKEN`, I'm unable to run most/all of the "kafka" subcommands available. I always get:

```
❯ rhoas kafka acl list 
❌ 400 Bad Request: invalid_grant: Offline user session not found. Run the command in verbose mode using the -v flag to see more information
```

### Steps to reproduce

1. Login into `rhoas` using an offline token with `rhoas login $OFFLINE_TOKEN`
2. Run `rhoas kafka list` or any other `rhoas kafka` subcommand
3. See the error above.

### Expected vs actual behaviour

Get the same result as I login using the default login method `rhoas login`, through the web browser.

### Logs

Running with `-v` as suggested by the error:

```
 rhoas kafka list -v
Checking for updates. Last check was done: 1659955216054
Refreshing tokens
Sending telemetery information for rhoas kafka list
❌ 400 Bad Request: invalid_grant: Offline user session not found. Run the command in verbose mode using the -v flag to see more information
```

**Comment by wtrocki** [comment]
Thank you for logging issue. We going to look into this

**Comment by wtrocki** [comment]
I cannot effectively replicate this issue. It might be outdated version of the CLI?

**Comment by wtrocki** [comment]
I can replicate the same message when I do:

1. Create new token 
2. Login using that token
3. Remove that token (invalidate it)
4. Execute dataplane command (or any command) 

That would imply that used token haven't been used for 30 days or have been manually invalidated

**Comment by joselsegura** [comment]
Interesting! I was using the token for handling `service-accounts` last week without any problem, but Kafka part give me problems. Now, I generated a new token and it works fine, so I guess this issue can be closed.

Thank you for pointing out my problem!
