### ISSUE TITLE
Support `service-registry` operations without AMS

### ISSUE THREAD

**Issue by andreaTP** [redhat-developer/app-services-cli#1710]
### Feature or problem description

It should be possible to run the CLI service-registry operations against an Apicurio installation that doesn't use AMS.
Currently, the CLI fails with a `404 Not Found.` error.

### Proposed solution

Make it possible to disable AMS checks in certain cases.

### Additional context

This feature can be tested against this local environment:
https://github.com/andreaTP/srs-fleet-manager/tree/enable-cli-on-k8s/dist/k8s-dev#start-multitenant-apicurio-registry-infrastructure-for-kubernetes-dev-mode

Running:
`rhoas login --api-gateway http://localhost:8081 --auth-url http://localhost:8083/auth/realms/demo-apicurio --client-id apicurio-cli`
and then:
`rhoas service-registry create`

**Comment by wtrocki** [comment]
Been on PTO. Fixing now.

**Comment by wtrocki** [comment]
This command would make registry create work without AMS
`rhoas service-registry create --bypass-checks`

**Comment by andreaTP** [comment]
Thanks @wtrocki , tested and working as expected 👍
