### ISSUE TITLE
ENH: CLI - simpler way to get a `CLUSTER_ID`

### ISSUE THREAD

**Issue by paoloantinori** [redhat-developer/app-services-cli#172]
Current docs here https://github.com/bf2fc6cc711aee1a0c2a/mas-guides/blob/master/common/creating-kafka.adoc suggest this expression to get a `CLUSTER_ID`:

```bash
CLUSTER_ID=$(rhoas kafka describe | jq .id -r)
```

we should consider a single command to get the information that would avoid piping the output to one or two commands to be usable.

It could be something like this:

```bash
source $(rhoas kafka get-cluster-id --id <id>)
```

Update: 
Current approach based on `jq` is better than the old one based on `grep` and `awk` but the final goal is probably to have this as a provided functionality by `rhoas`.

**Comment by wtrocki** [comment]
This seems to be resolved. 

Status command exists. Describe accepts id
