### ISSUE TITLE
Service Account list returns list instead of object

### ISSUE THREAD

**Issue by henryZrncik** [redhat-developer/app-services-cli#1728]
## Description

**[0.50.0-beta1]**: 

### Steps to reproduce

`rhoas service-account list -o json`
command will pass in cli but not in case we parse JSON as object in Java.  

#### Obtained 
obtained output will be list of service accounts (i.e. list of JSON objects) 
#### expected
one object with multiple items, expected from  Kafka Management SDK 0.24 in form of `ServiceAccountList` class.

**Comment by wtrocki** [comment]
@rkpattnaik780 I think we need to discuss moving service account migration to feature branch for now.

This is breaking change with huge impact to existing integrators
