### ISSUE TITLE
Created namespace is being set as connector in the context

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1758]
## Description

Currently, the command `rhoas connector namespace create` saves the created namespace as connector in the current context. It should be changed to save it as namespace.

Changes need to be done [here](https://github.com/redhat-developer/app-services-cli/blob/e69eae60b7656e93fdd8394f980f83d59444996b/pkg/shared/contextutil/util.go#L208).

**Version**: 0.51.2

### Steps to reproduce

1. Create a connector namespace:

```
rhoas connector namespace create --name test
```
3. Run `rhoas status namespace`
4. You should get an error - No services set

### Expected vs actual behaviour

Created namespace should be set as namespace in the context and not as connector.

**Comment by wtrocki** [comment]
Critical issue. Not for hacktoberfest.
