### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1761]
It will be great to have some badges in the README file like [Go version](https://img.shields.io/github/go-mod/go-version/gomods/athens.svg), [Go report card](https://godoc.org/github.com/redhat-developer/app-services-cli?status.svg) and [License](https://img.shields.io/badge/license-Apache--2.0-blue.svg).

**Comment by jsvigneshkanna** [comment]
Please assign this to my name, will implement this

**Comment by rkpattnaik780** [comment]
Go ahead @jsvigneshkanna .
