### ISSUE TITLE
Localize strings in request command

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#1767]
The short description, long description and example for the `request` command currently use [raw strings](https://github.com/redhat-developer/app-services-cli/blob/main/pkg/cmd/request/request.go#L38-L45). They should be localized as in other commands. You can refer to [this example](https://github.com/redhat-developer/app-services-cli/blob/main/pkg/cmd/whoami/whoami.go#L34-L36).

A new `toml` file needs to be added to `pkg/core/localize/locales/en/cmd`, whose keys should then be used in the `request` command using the `localizer` object.

This will also fix the indentation of `rhoas request` help text.

**Comment by yati1998** [comment]
Can I work on this?
