### ISSUE TITLE
CLI version command can check if CLI wasn't updated 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#178]
We can use github releases (currently private) for checking if the version is the latest.

**Comment by wtrocki** [comment]
This can be extended for breaking changes detection before we go to the 1.0 release

**Comment by craicoverflow** [comment]
So is the suggestion to print to the terminal that a version update is available?

I like the idea, but it can be a fine line between being annoying and useful.

```
$ rhoas whoami
A new version is available! Run blah blah bl;ah to update
ephelan_kafka_devexp

$ rhoas kafka list
A new version is available! Run blah blah bl;ah to update

<LIST OF KAFKAS>
```

**Comment by craicoverflow** [comment]
![image](https://user-images.githubusercontent.com/11743717/115032615-6b3d7a80-9ec1-11eb-9a90-4734135c8d5f.png)

We could show this when the user logs in, which usually only happens once per day.
