### ISSUE TITLE
`-o=web` to open the current CLI context in the web UI

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#317]
It would be really nice if you could run `rhoas kafka describe -o=web` which would then open `https://qaprodauth.cloud.redhat.com/beta/application-services/openshift-streams/kafkas/{current-kafka-id}` in the browser.

This flag could be applied in numerous places such as `kafka list -o web`, `topic list -o web` etc.

**Comment by wtrocki** [comment]
Proper requirement will be to get backend UI URL returned as we got for registry. Logging with separate team and closing as there will be no action on our side.

**Comment by craicoverflow** [comment]
This would eventually be actionable on our side though right? control planes probably won't return a UI URL, nor would kafka data plane.

**Comment by wtrocki** [comment]
Done already for srs. It should return UI url

**Comment by craicoverflow** [comment]
So there is a flag there which when passed will automatically open the UI in the browser?

**Comment by wtrocki** [comment]
backend returns URL for every metadata for registry. Will ask if we can get it for kafka. Reopening
