### ISSUE TITLE
[Enhancement Idea] I want to be able to have multiple profiles to easily switch environments

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#350]
Currently, I have to either re-login or manually edit the config file if I want to switch environments between dev/prod/staging.

It should be possible to create, list and switch between profiles.

Set the current profile:

```
$ rhoas profile set development
You are now in the "development" profile as "ephelan" 
```

Listing profiles:

```shell
$ rhoas profile list
development
production
staging
```

**Comment by wtrocki** [comment]
That would be user-facing command to solve problem only for us (not real users)
Would profile work with different accounts as well?

**Comment by craicoverflow** [comment]
yeah you are right. There is no need.

**Comment by craicoverflow** [comment]
I was thinking about this again - maybe it can be re-framed in terms of having multiple application contexts instead?

I as a developer may be working on multiple separate projects with `rhoas`. I want clean separation between these applications, meaning I do not want to have to run `rhoas [service] use` on each service to switch to a different project.

It would be convenient to have the ability to switch application context easily, where each context has a separate set of "used" services.

**Comment by wtrocki** [comment]
@craicoverflow Next year we need ADR and push for project/environments abstraction. 
I'm not 100% sure if we should invest more into CLI only as the main focus right now is in the UI. 

If there is abstraction like that we want that in UI, CLI and... most likely Operator/OpenShift binding integration. 
What we have in CLI right now is just low effort replacement for that.

**Comment by wtrocki** [comment]
That being said. We can replace use with another hack, but this would be not an ideal solution due to lack of lifecycle management on thise. Currently, user context can be outdated (your selected Kafka might not exist etc.)
I do see this as very low priority due to other commitments and the fact that we need to have it solved the complex way with OpenShift integration etc.

**Comment by craicoverflow** [comment]
Will be done in #1306

**Comment by wtrocki** [comment]
@craicoverflow thank you for finding this. In this issue we have raised very valid concern that we will need to solve. 

Profiles need to be validated before executing - we need to check if services still exist etc.
