### ISSUE TITLE
API update script should be using github instead of gitlab

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#456]
### Feature or problem description

Challenge is that repo is private so standard way to get raw content will not work. 
Instead of that we can use `git export` feature.

wget --no-check-certificate https://raw.githubusercontent.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/main/openapi/kas-fleet-manager.yaml

**Comment by craicoverflow** [comment]
Soon to be obsolete by the SDK.
