### ISSUE TITLE
[Suggestion] Better handling for pending state for cluster creation

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#51]
Cluster that is currently pending should have special handling to not request topics etc.

**Comment by wtrocki** [comment]
@craicoverflow this was mentioned couple times during UX review. 
Adding to backlog

**Comment by craicoverflow** [comment]
Yep I had brought that up. We actually have a duplicate here: https://github.com/redhat-developer/app-services-cli/issues/604

**Comment by wtrocki** [comment]
Closing this one as the other one is more specific
