### ISSUE TITLE
Remove double login

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#548]
It should be possible to remove the double-authentication which was required up until now.

**Comment by craicoverflow** [comment]
hey @akoserwal do you know how this will work? Should I just need to authenticate to MAS-SSO, and the single token would work for both servers, or is it more complex than this?

**Comment by akoserwal** [comment]
Double-auth will be required. For api token from sso & mas-sso for the dataplane

**Comment by craicoverflow** [comment]
Thanks. Do you know why there were some discussions around double-login being "dead" now?

> The most impactful change is that
identity brokering is now enabled with Red Hat SSO, which means the
dreaded double login is now DEAD.

This is a quote from an email. Does this only apply to the UI?

**Comment by akoserwal** [comment]
it is only for UI, where users don't see a double login screen. But behind the scene UI/Cli will need 2 tokens

**Comment by craicoverflow** [comment]
https://github.com/redhat-developer/app-services-cli/pull/561

@wtrocki we won;t be able to handle this for the token login flow sadly.
