### ISSUE TITLE
Refactor util method to create ConfigEntries for TopicSettings

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#555]
### Enhancement description

The util method to create config entries while creating/updating a topic uses specific field as an argument (which is retenPeriod for now). This method can get bit cumbersome if we are to add multiple config entries.

### Proposed solution

The [CreateConfig](https://github.com/redhat-developer/app-services-cli/blob/main/pkg/kafka/topic/util.go#L14) should accept a map and return array of configEntries according to it. It should check for null strings in order to determine which fields are to be updated.

**Comment by craicoverflow** [comment]
I like the solution proposed, it should be way more elegant and scalable!
