### ISSUE TITLE
Command completion incorrect for "rhoas kafka topic"

### ISSUE THREAD

**Issue by bhardesty** [redhat-developer/app-services-cli#566]
## Description

**Version**: 0.22.0

Command completion for "rhoas kafka topic" incorrectly completes to "rhoas kafka topics" (note the extra "s" at the end).

### Steps to reproduce

1. Type "rhoas kafka t"
2. Press tab.
3. See that the command auto-completes to "rhoas kafka topics".
4. Press Enter.
5. The help text is displayed for "rhoas kafka" since "topics" is an invalid subcommand.

**Comment by craicoverflow** [comment]
Thanks @bhardesty .. can I ask what shell you are using? Shell, Zsh, Fish or something else?

**Comment by craicoverflow** [comment]
I think you may have an old completion script installed. If you run the `completion` command again, it may update? The topic command used to be `topics` in previous versions, but the Bash completion script is static.

**Comment by bhardesty** [comment]
@craicoverflow I'm using bash, and you're correct - I had an older version of the bash command completion installed. I just updated it, and the "topic" command is completed correctly. Closing this, and sorry for the extra noise!
