### ISSUE TITLE
Get topic list as JSON returns message instead of empty list

### ISSUE THREAD

**Issue by b1zzu** [redhat-developer/app-services-cli#579]
## Description

**Version**: rhoas version 0.22.1

### Steps to reproduce

1. Create a new Kafka instance and use it
2. Run `rhoas kafka topic list -o json`

### Expected vs actual behaviour

I expected it to return the standard JSON object with empty items: `{"items": []}`
but I got this message: `Kafka instance "test-dbizzarr" has no topics. Run "rhoas kafka topic create <topic-name>" to create one`

**Comment by b1zzu** [comment]
@craicoverflow Should we fix this on the CLI, wdyt?

**Comment by craicoverflow** [comment]
Yeah, I agree with this. However this could break things for people using the CLI, so let's check the wider impact before doing it.

**Comment by b1zzu** [comment]
the idea here is when using the `-o json` option, otherwise, it should report the message if empty

**Comment by craicoverflow** [comment]
This has been included in the latest alpha release https://github.com/redhat-developer/app-services-cli/releases/tag/0.23.0-alpha3.

Thanks again for logging the issue!

**Comment by b1zzu** [comment]
@craicoverflow tests have already pick it up :)
