### ISSUE TITLE
Set Args to zero for appropriate commands

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#580]
## Description

Commands that do not accept any positional arguments should have the `Args` property set to `NoArgs`.

**Version**: 0.22.0

### Steps to reproduce

1. Run `login` command with random trailing words.
```
go run ./cmd/rhoas login kafka topic list
```

### Expected vs actual behaviour

It should fail throwing some error but it successfully opens a tab in browser to login.

![Screenshot from 2021-04-16 13-13-09](https://user-images.githubusercontent.com/23582438/114991001-bb630f80-9eb6-11eb-91e6-d726ae019fe8.png)

Can be seen in `whoami` as well:

![Screenshot from 2021-04-16 13-27-57](https://user-images.githubusercontent.com/23582438/114991784-9b801b80-9eb7-11eb-9c46-ee586d49b59b.png)

**Comment by craicoverflow** [comment]
Thanks, good catch!

**Comment by craicoverflow** [comment]
I've realised we should set args to n for the other commands too. For example `rhoas cluster` should have `ExactArgs(1)`.
