### ISSUE TITLE
[Cluster] Selecting Kafka that is not available on cluster should automatically create it 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#590]
### Feature or problem description

Currently we require rhoas cluster connect and rhoas cluster bind commands to be executed. 
Technically we can simplify this for user to automatically connect kafka when binding. 

Needs PM feedback. CC @duncandoyle

**Comment by craicoverflow** [comment]
What's the ask here? To create a kafka cluster automatically if it does not exist?

**Comment by wtrocki** [comment]
@craicoverflow this is to create connections when trying to bind current Kafka. Cluster needs to exist for it.
After collecting feedback I think this feature should be considered priority for the service registry integration.

**Comment by craicoverflow** [comment]
I'm just wondering if that is a side effect? What if the user mistyped the cluster name, and it instead goes and creates a new one for them.

**Comment by wtrocki** [comment]
Missunderstanding. This issue doesn't create a cluster. It will create Kafka connection in cluster and bind it (think of connect and bind run in single command). We will use the same logic and ask user for confirmation meaning that there is no accidental creation of kubernetes resource.

**Comment by wtrocki** [comment]
We are moving to bind command being able to list MKC objects on cluster rather than pulling API. This issue is not relevant anymore
