### ISSUE TITLE
When logging using login --token kafka topic commands are not available

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#594]
### Feature or problem description

`rhoas login --token` is used when logging inside containers (also part of the OpenShift quickstarts).

This form of login will not give us access to MAS-SSO (that requires it's own token) and currently 
returns information that user needs to login again.

## Possible solutions

1. (Suggested) Improve error message to show that when logging with token all consumergroups and topics commands are not enabled.

2. Research if we can use sso.redhat.com offline token to obtain mas-sso token with federation. (Unlikely)

**Comment by craicoverflow** [comment]
For solution 1 - we can detect if the client ID is "cloud-services" - and if so this means data plane is not available.

**Comment by wtrocki** [comment]
Would it be easier to check for SSO token to be available - Making sure that is emptied when logging using token?
Client ID sounds very specific to our implementation/current setup.

**Comment by craicoverflow** [comment]
There could be other cases where the MAS-SSO token is not available though, for whatever reason, like if the user closes the login page before it has the change to perform a federated login, or a lost network connection.

The client ID is embedded into the implementation already: https://github.com/redhat-developer/app-services-cli/blob/main/pkg/cmd/login/login.go#L83-L85

Actually, probably a better way to do this is with the `scopes` JWT claim:

```
{
  "iat": ...,
   ...
  "scope": "openid offline_access"
}
```

`offline_access` - token login.

**Comment by wtrocki** [comment]
Since we are federated - both logins will be instant so technically small chance of closing second tab, but even though my take is to not hardcode things when token is passed but simply react to SSO token is missing with proper message that will also pretty much handle corner cases you have mentioned:

`You cannot access Kafka specific functionalities at the moment because of missing authentication token. Please consider login again (without --token option)`

That message solves all corner cases and will not require any change than i18n
