### ISSUE TITLE
Kafka create command states that instance is created when it's actually not ready yet

### ISSUE THREAD

**Issue by ppatierno** [redhat-developer/app-services-cli#601]
When asking for a Kafka creation, the CLI reports something like this

```shell
./rhoas kafka create
? Name: ppatiern
? Cloud Provider: aws
? Cloud Region: us-east-1
Kafka instance "ppatiern" created successfully
{
  .... omitted ... 
  "status": "accepted",
  "updated_at": "2021-04-19T20:33:22.269278439Z",
  "version": "2.7.0"
}
```

It means that the cluster is not really created but it's provisioning.
It's clear when running this

```shell
./rhoas kafka describe
{
  ... omitted ... 
  "status": "provisioning",
  "updated_at": "2021-04-19T20:33:51.868111Z",
  "version": "2.7.0"
}
```

And finally the "status" moves to "ready". 
So I think that the sentence `Kafka instance "ppatiern" created successfully` should be more `Kafka instance "ppatiern" is going to be provisioned` or something similar.

**Comment by craicoverflow** [comment]
You are absolutely right! Thanks, that is great feedback.
