### ISSUE TITLE
Synchronous/Wait Kafka instance creation

### ISSUE THREAD

**Issue by ppatierno** [redhat-developer/app-services-cli#604]
Related to #601 which is now addressed, I was thinking about my experience with the Azure CLI.
With that CLI you can specify a --no-wait parameter to start a long-running operation asynchronously; the rhoas CLI is somehow async by default.
When creating a new Kafka instance, it starts the provisioning and you have to use the status command to see the progress.
Maybe having a --wait parameter could be useful to make it synchronous so having the CLI to block and check periodically the status of the provisioning and exiting when the Kafka instance is actually ready.

**Comment by machi1990** [comment]
Related to https://github.com/redhat-developer/app-services-cli/issues/41

**Comment by wtrocki** [comment]
Does backend supports watch? We could do pooling for this as well

**Comment by machi1990** [comment]
> Does backend supports watch? 

No, the backend does not support watch or synchronous creation. Polling is a good workaround.

**Comment by craicoverflow** [comment]
Backend does not yet support synchronous creation. Once it is possible this is definitely something that will be added.

**Comment by machi1990** [comment]
> Backend does not yet support synchronous creation.

It is unlike that synchronous creation will be supported by the backend.

**Comment by craicoverflow** [comment]
> > Backend does not yet support synchronous creation.
> 
> It is unlike that synchronous creation will be supported by the backend.

Good to know. Is the `async=true` query param going to remain as a "just in case" measure?

**Comment by machi1990** [comment]
> > > Backend does not yet support synchronous creation.
> > 
> > 
> > It is unlike that synchronous creation will be supported by the backend.
> 
> Good to know. Is the `async=true` query param going to remain as a "just in case" measure?

This will always remain and it is a required parameter indicate that the operation will be performed in async manner. If you set it to `false` I believe the request should fail even now with a `400` HTTP code.
