### ISSUE TITLE
OAuthBearer config token endpoint is not provided when using CLI for connecting to kafka

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#607]
### Feature or problem description

https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token is the token endpoint that should not change in near future. We should think about some way to expose that endpoint to user as he would need it to configure it's kafka for Quarkus/Node.js

```
%dev.kafka.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  oauth.client.id="${CLIENT_ID}" \
  oauth.client.secret="${CLIENT_SECRET}" \
  oauth.token.endpoint.uri="${OAUTH_TOKEN_ENDPOINT_URI}" ;
```

UI currently differentiates between credentials for SASL/Plain (changes keys for those) and OAUTH/BEARER - prints token URL when presenting credentails.

For CLI we could do some easy wins here - add some note to serviceaccounts help? New flag that will add token when requesting credentials/change keys - to mimick what UI does?

**Comment by craicoverflow** [comment]
I'm weary of adding a "quick win" to be honest, as it means we may remove it in the future. Should this information stay in the guides?

**Comment by wtrocki** [comment]
Yes I agree. This was just part of the discussion so my take is to leave it open. 
If we do not look for quick wins then my take is that kas API should be returning this value for service and it should be visible in describe. Something like that would be satisfactory? I can see how to add this to kas-api now.

I have planned to add this to the guide (in PR state) so we covered on this front.

@craicoverflow

**Comment by craicoverflow** [comment]
> If we do not look for quick wins then my take is that kas API should be returning this value for service and it should be visible in describe. Something like that would be satisfactory? I can see how to add this to kas-api now.

Agreed. Presuming you mean the `serviceaccount describe` command?

**Comment by wtrocki** [comment]
More like `rhoas kafka describe -o json`

...
tokenUrl: "..."
...

**Comment by wtrocki** [comment]
Great example that we need to do better backlog refinements. 

Issue from `20 Apr` that resurfaced recently as critical (I created new issue)

**Comment by wtrocki** [comment]
Btw.. at the time we were kafka centric. This was implemented in service accounts (where it should be)
