### ISSUE TITLE
[Question/Bug]

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#614]
rhoas CLI uses 7 days as the default value for topic retention time, whereas the UI uses one day. The default value used to be 7 days and they were aligned at one point.

See below, topic-1 was created in the UI and topic-2 created using CLI, both with default retention values.

```shell
❯ rhoas kafka topic list
  NAME      PARTITIONS   RETENTION TIME (MS)   RETENTION SIZE (BYTES)  
 --------- ------------ --------------------- ------------------------ 
  topic-1            3   86400000              -1 (Unlimited)          
  topic-2            2   604800000             -1 (Unlimited)          
```

@rkpattnaik780 which should it be?

**Comment by rkpattnaik780** [comment]
Default retention time is 1 week for the UI as well. It must be arising due to some bug, we will have a look.
