### ISSUE TITLE
When deleting a Kafka instance, it should say "Kafka instance being deleted" or similar

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#615]
As the Kafka instance will not immediately be deleted.

```shell
❯ rhoas kafka delete
Deleting Kafka instance "endas-kafka" 

? Confirm the name of the instance you want to delete: endas-kafka
Kafka instance "endas-kafka" has successfully been deleted
❯ rhoas kafka list
  ID                            NAME          OWNER             STATUS        CLOUD PROVIDER   REGION     
 ----------------------------- ------------- ----------------- ------------- ---------------- ----------- 
  1rTupXoZVEhaS3XYshEbi7XqMo4   endas-kafka   kafka-chocolate   deprovision   aws              us-east-1  
```

**Comment by rkpattnaik780** [comment]
![Screenshot from 2021-06-03 17-53-25](https://user-images.githubusercontent.com/23582438/120644830-66df1800-c495-11eb-94ae-1a14c5498ff2.png)
![Screenshot from 2021-06-03 18-05-10](https://user-images.githubusercontent.com/23582438/120645650-4794ba80-c496-11eb-87a1-660ec41ac2b7.png)

The proposed solution feels bit weird, I have a few suggestions:
- `Deleting Kafka instance "rama-test"` and `Kafka instance "rama-test" is being deleted` basically say the same thing in different voice. Should the first statement be imperative, like `Delete Kafka instance "rama-instance"?`
- We should show only one message when `--y` flag is passed, i.e `Kafka instance "rama-test" is being deleted` 
 wdyt @craicoverflow ?

**Comment by craicoverflow** [comment]
I think we should only show one message - choose one of those messages and show it.
