### ISSUE TITLE
Add a spinner to give visual feedback when making API requests

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#616]
Possible library: https://github.com/briandowns/spinner

**Comment by wtrocki** [comment]
Side note: This was mentioned as part of the UX feedback.

**Comment by wtrocki** [comment]
@craicoverflow I saw you adding spinner to login etc.. which is ok
IMHO spinner for API requests is a gimmick that would not work well in:

- OpenShift terminal (workshops)
- Windows cmd

Leaving you to reopen.
