### ISSUE TITLE
RHOAS login unavailable in headless environments

### ISSUE THREAD

**Issue by hawkdshrh** [redhat-developer/app-services-cli#617]
Because rhoas login pops up a browser window, it does not work in a headless environment.  Instead, it fails with a cryptic "Error: exit status 3" message. Many customers work in virtualized / headless environments or have rsh / ssh access only to connected environments, so this may be a blocker for them.

**Comment by b1zzu** [comment]
ping @craicoverflow

**Comment by wtrocki** [comment]
Please use --token option to use token based login.
This will work for all commands apart from topics and consumer groups - which also can be managed using any upstream tool.
If you looking for user driven flows there is also code ready derived operator that opens browser

**Comment by wtrocki** [comment]
Additionally we have quay.io/RHOSAK/tools image done by @DuncanDoyle that wraps CLI and guide that covers how to use CLI in that env

**Comment by hawkdshrh** [comment]
@wtrocki is there some doc on how to set up token-based login?  I didn't see any or options for setting up rsa or other access in the user settings page.

**Comment by b1zzu** [comment]
@wtrocki I think it would be also nice to have something different from a "Error: exit status 3" as message

**Comment by wtrocki** [comment]
Yes. I do not question bugs:

1. Cryptic message
2. Token option do not document that you should use https://cloud.redhat.com/openshift/token

**Comment by craicoverflow** [comment]
Thanks for raising this issue.

Yeah, definitely a cryptic message, apparently it means "no such process".

Could you paste the exact output that you saw including this error message to help me pinpoint where in the program it occurs?
Could you also let me know the OS of the headless environment?

> Token option do not document that you should use cloud.redhat.com/openshift/token

It does:

```
root@2b829e16b34e:/# rhoas login -h
Log in securely to RHOAS through a web browser.

This command opens your web browser, where you can enter your credentials.

Usage:
  rhoas login [flags]

Examples:
# securely log in to RHOAS by using a web browser
$ rhoas login

# print the authentication URL instead of automatically opening the browser
$ rhoas login --print-sso-url


Flags:
  ...
  -t, --token string          Allows you to log in using an offline token, which can be obtained at https://cloud.redhat.com/openshift/token.
```

Though you're right @wtrocki it should also be included in the help description.

**Comment by craicoverflow** [comment]
#620 will provide better documentation for the current login limitations.

**Comment by hawkdshrh** [comment]
@craicoverflow - Do you have ssh / sshd in your envirnment?  If so, try these steps:

$ ssh localhost (accept key / cet)
$ rhoas login
Logging in...
Error: exit status 3

**Comment by craicoverflow** [comment]
> @craicoverflow - Do you have ssh / sshd in your envirnment? If so, try these steps:
> 
> $ ssh localhost (accept key / cet)
> $ rhoas login
> Logging in...
> Error: exit status 3

Thanks,

I did not know you could do this!

**Comment by hawkdshrh** [comment]
Sure thing!

**Comment by craicoverflow** [comment]
I have added a potential fix to this in https://github.com/redhat-developer/app-services-cli/pull/624

But I have not been able to reproduce this yet so it is a shot in the dark. If anyone had a minute to verify what happens that would be really helpful!

I will continue trying to reproduce this situation.

**Comment by wtrocki** [comment]
I think we support token for headless environment. Lack of the dataplane support is limitation of our architecture that we do not control and it should improve
