### ISSUE TITLE
Printing xterm colors in windows cmd

### ISSUE THREAD

**Issue by kornys** [redhat-developer/app-services-cli#621]
## Description

**Version**:0.23.1 

on windows cmd after successful login rhoas prints url which uses xterm colors but it is not interpreted in windows cmd.

### Expected vs actual behaviour

In windows cmd line

### Logs
```
You are now logged in as "kafka-german-pilsner"

[96mA new version of rhoas is available:[0m [95m0.23.1[0m
[96mhttps://github.com/redhat-developer/app-services-cli/releases/tag/0.23.1[0m
```

**Comment by craicoverflow** [comment]
Do Windows users still use Command Prompt? Windows Powershell supports these colours just fine.

https://stackoverflow.com/a/38617204

**Comment by kornys** [comment]
@craicoverflow well it depends, windows contains cmd and powershell by default, but you are also able to install new teminal env. anyway from user experience cmd is a default env for developers/administrators
