### ISSUE TITLE
Rewrite README

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#655]
The README is a little bit...bare.

The CONTRIBUTING document is too heavy on content, much of that should be in the README, if we were to follow common practices.

I'm not going to enforce any strict structure, as there are multiple variations and they are all the time getting better and better.

Check out https://github.com/matiassingers/awesome-readme for inspiration.

For Go projects, look at https://github.com/avelino/awesome-go. There may be Go-specific things we can have on the README like pkg.go.dev badges.

**Comment by rkpattnaik780** [comment]
Could find a few badges that will look good on the readme :)

 [![GoDoc](https://godoc.org/github.com/redhat-developer/app-services-cli?status.svg)](https://pkg.go.dev/github.com/redhat-developer/app-services-cli)
[![Go Report](https://goreportcard.com/badge/github.com/redhat-developer/app-services-cli)](https://goreportcard.com/report/github.com/redhat-developer/app-services-cli)
[![GitHub go.mod Go version of a Go module](https://img.shields.io/github/go-mod/go-version/gomods/athens.svg)](https://github.com/redhat-developer/app-services-cli)

These will require some changes in the codebase as well, for ex the go report grades are too poor and godocs dont look that useful.

For the README structure, adding installation instructions and a one-line description of the CLI along with a screenshot (like the one in [gh cli](https://user-images.githubusercontent.com/98482/84171218-327e7a80-aa40-11ea-8cd1-5177fc2d0e72.png)) will make it more useful. What do you think?

**Comment by craicoverflow** [comment]
I don't think a screenshot makes it more useful necessarily, it can go out of date quicker than high level documentation. Giving you creative control on this though :)

Look at projects other than GitHub CLI though like kubectl and gcloud which aligns more with our offering.

**Comment by rkpattnaik780** [comment]
> I don't think a screenshot makes it more useful necessarily, it can go out of date quicker than high level documentation. Giving you creative control on this though :)
> 
> Look at projects other than GitHub CLI though like kubectl and gcloud which aligns more with our offering.

Put it wrongly. screenshot is for a better look, not usefulness, not sure if we should stick to it. Let me try some combinations.

**Comment by craicoverflow** [comment]
This will also close https://github.com/redhat-developer/app-services-cli/issues/622

**Comment by wtrocki** [comment]
README.md should mention install script or releases for installation.
Additionally install script can be available as part of the release files (so it is versioned properly etc.)

**Comment by wtrocki** [comment]
This can be sourced into 4-5 micro issues
