### ISSUE TITLE
Rewrite CONTRIBUTING.md

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#656]
This work should come _after_ #655

The CONTRIBUTING guide is too heavy on development set up, whereas in my view it should be more focused on minimal contribution guidelines which provide recommendations on issue and pull request creation.

Here are a couple of CONTRIBUTING examples: 

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md

https://github.com/cli/cli/blob/trunk/.github/CONTRIBUTING.md

**Comment by wtrocki** [comment]
Since then Contributing changed and it is light enough (at least for me). @craicoverflow WDYT? Can we close this?

**Comment by craicoverflow** [comment]
Yes
