### ISSUE TITLE
Short and Long description should be unified.

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#658]
rhoas kafka has only short descriptions. some commands use long ones etc. 
My take is that we might need to:

- Remove i18n from use (command name)
- Unify long descriptions on root commands
- Improve overall help messages

**Comment by craicoverflow** [comment]
> Remove i18n from use (command name)

Agreed.

> Unify long descriptions on root commands

Do you mean maybe only have the long description?

**Comment by wtrocki** [comment]
More like if one root has long description others should too. Best to have both and utilize those to put more info

**Comment by wtrocki** [comment]
This was done thanks to @namit-chandwani and @ankithans for making validator and implementing it in rhoas
