### ISSUE TITLE
Add auto completion for flags

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#682]
### Feature or problem description

CLI should have auto completion for flags wherever possible.

### Proposed solution

Flags such as `--output` should be able to autocomplete themselves based on allowed values.

**Comment by craicoverflow** [comment]
Some more flags I have found:

```shell
rhoas kafka consumergroup list --topic <dynamic-value>
rhoas kafka create kafka-1 --provider <dynamic-value> --region <dynamic-value>
```

**Comment by craicoverflow** [comment]
Ah, I see you have already gotten to some of them @rkpattnaik780 :)
