### ISSUE TITLE
Missing i18n key in serviceaccount create

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#694]
## Description

**Version**: #

The `serviceaccount create` command uses an undefined key `"flag.error.required"`.

### Steps to reproduce

1. Run `rhoas serviceaccount create --name kafka-test`
2. You should get the error `panic: message "flag.error.required" not found in language "en"`

**Comment by craicoverflow** [comment]
@rkpattnaik780 should this be closed? Can you go through the issues and check if the issues were closes correcttly from your PRs? :)

**Comment by rkpattnaik780** [comment]
This can be closed. I was expecting it would be closed after PR merge. Thanks for the nudge. :)

**Comment by rkpattnaik780** [comment]
Fixed in #696
