### ISSUE TITLE
Improve search functionality for Kafka instances

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#698]
The current implementation of `--search` for `rhoas kafka list` returns matches after searching against all the columns. Should this be modified to be column specific like the filters implemented in `kas-ui`.

**Comment by craicoverflow** [comment]
Any changes like this to the CLI now would be a breaking change, which we should try to avoid. I think searching against all columns is a nice UX.

**Comment by craicoverflow** [comment]
Can we close this @rkpattnaik780 ?
