### ISSUE TITLE
Provide more accurate logs when running Kafka data plane commands

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#712]
I have deleted a Kafka instance from the UI and try to run a topic command - the message makes it sound as thought the cluster is being created:

```
❯ rhoas kafka topic list
Error: Kafka instance "enda-test" is not ready yet
```

We should provide a different message depending on the current Kafka instance state.

**Comment by rkpattnaik780** [comment]
Closed by #729
