### ISSUE TITLE
Release workflows running for unintended tags

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#715]
## Description

Creating a tag without "v" prefix still runs the workflow for changelog generation. The tag pops up in the list of releases as well.

An instance of occurrence - https://github.com/redhat-developer/app-services-cli/actions/runs/928330246

![Screenshot from 2021-06-11 16-51-25](https://user-images.githubusercontent.com/23582438/121878362-40d53580-cd29-11eb-8563-8a08a91ebdfc.png)

### Expected vs actual behaviour

Changelog should be generated only for tags that are prefixed with `v`.

**Comment by wtrocki** [comment]
we can use pattern matching for running github actions job. `v is required`.
Pattern is already preset in the changelog config so we can copy that to github actions with some modifications for prerelease:
https://github.com/redhat-developer/app-services-cli/blob/main/.chglog/config.yml#L7
