### ISSUE TITLE
Add unit tests to cover all validators

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#717]
It is unnecessary to unit test the commands, but I feel that we should have unit tests to cover all/most validator functions.

A good example of what we have already: https://github.com/redhat-developer/app-services-cli/blob/f00da5a016e07e0dea00145e99fc4d73145efd9a/pkg/kafka/topic/validators_test.go#L6

We should roll this out to other validators.

**Comment by rkpattnaik780** [comment]
closed by #728
