### ISSUE TITLE
Email field is user token is not set as the users email

### ISSUE THREAD

**Issue by davidffrench** [redhat-developer/app-services-cli#719]
## Description

**Version**: Unsure, reported by another user

### Steps to reproduce
1. Login using the CLI
2. View the generated user token
3. Verify the email field in the token is always set to "ms-devexp@redhat.com"

### Expected vs actual behaviour
The email field should map to the users email

**Comment by craicoverflow** [comment]
As far as I know this field would be set by sso.redhat.com when it returns the JWT to the CLI. 

I _think_ that the way this is set up is that it intentionally maps to the user's organization.

@akoserwal would you be able to confirm whether this is correct or not?

**Comment by akoserwal** [comment]
@craicoverflow: email field should map with the user who logged in. Currently it returns:   "email": "ms-devexp@redhat.com".
I will open a ticket with IT team to get the clients fixed

**Comment by wtrocki** [comment]
Bumping topic to see if we got update from IT team

**Comment by craicoverflow** [comment]
Actually this was resolved last week.
