### ISSUE TITLE
Configure renovate

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#724]
https://docs.renovatebot.com/golang/

We should configure renovate to keep Go Module dependencies updated.

- patch updates can be auto-merged
- minor and major version updates can have a pull request created with the bump but should not be auto-merged.

**Comment by wtrocki** [comment]
https://github.com/redhat-developer/app-services-cli/pull/708

**Comment by craicoverflow** [comment]
Okay. Let's not merge this until after code freeze.
