### ISSUE TITLE
Remove mistakes and dead code 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#750]
## Description

Adjust golangci lint 
Number of tools available:

https://medium.com/wesionary-team/introduction-to-linters-in-go-and-know-about-golangci-lint-6486fb2864b3

after running all or linters I got some changes in code.

**Comment by craicoverflow** [comment]
Could you include these linters into our Linting config to help enforce this?

**Comment by wtrocki** [comment]
I think golangclilint have them already. Trick is that each of them needs to be configured - some of them are pretty cpu intensive and disabled by default. I would like to do it slowly to understand what those linters do etc.
We can apply quick wins fast for sure.
