### ISSUE TITLE
Merge kafka crud i18n into single file

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#757]
## Description

Currently navigation between multiple files/common elements is very hard. 

We should have developer UX oriented i18n (not file oriented that causes a lot of confusion and has number of entries duplicated). Without using single file we cannot detect duplicates which are currently in main branch.

## Proposed files
```
kafka_crud.en.toml
registry_crud.en.toml
serviceaccount_crud.en.toml
cluster_en.toml
kafka_consumer_group.en.toml
kafka_topics.en.toml
```

**Comment by craicoverflow** [comment]
Agreed, we could even do `kafka.en.toml`, `serviceregistry.en.toml` instead without going down to the different subcategories.

By the way, please use the `bug` label lightly (for actual bugs only 😉).

**Comment by wtrocki** [comment]
Sorry for wrong label.

**Comment by wtrocki** [comment]
At this point I'm not sure if that is good idea. 
Having i18n file mapping source file is ok but we now have lots of common flags that replicate.

**Comment by alexal** [comment]
@wtrocki , @craicoverflow please review PR #993
