### ISSUE TITLE
Add ability to update the cleanup policy for a Kafka topic

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#772]
### Feature or problem description

User should be able to modify the cleanup policy for Kafka topic using `kafka topic update` for both normal and interactive mode.

### Proposed solution

Add `--cleanup-policy` flag for `kafka topic update`.

**Comment by rkpattnaik780** [comment]
To be done after #769

**Comment by rkpattnaik780** [comment]
@craicoverflow , for having a `survey.select` in edit mode, I am thinking to show all the options with the original cleanup selected by default, does that sound good to you?

**Comment by craicoverflow** [comment]
Yeah that sounds good! It actually might make sense to do that for the other fields that are already able to be updated, would that remove the weird hack of converting from a string?

**Comment by rkpattnaik780** [comment]
> Yeah that sounds good! It actually might make sense to do that for the other fields that are already able to be updated, would that remove the weird hack of converting from a string?

Not sure what you mean by other fields here, this one is bit different cause it has a range of values, all strings so no need of conversion.
However one drawback in the current PR is it makes an API request for update even if user doesn't set a new cleanup policy. Should we put a comparision such that update will be needed when opts.cleanupPolicy != currentTopic.cleanupPolicy

**Comment by craicoverflow** [comment]
Ignore me, upon checking I remembered why what I am suggesting would not work.

> Should we put a comparision such that update will be needed when opts.cleanupPolicy != currentTopic.cleanupPolicy

Yeah I like the sound of that.

**Comment by rkpattnaik780** [comment]
Updated in the PR. :)
