### ISSUE TITLE
Conventional commits validator fails for valid commits

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#784]
## Description

@craicoverflow It will be good to remove this job across the fleet and use conventional commits bot.

I actually never managed to let it pass on my commit despite they were aligned with spec.

**Comment by craicoverflow** [comment]
> subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]

https://github.com/redhat-developer/app-services-cli/pull/783

There is your problem. You should not be using upper-case.

**Comment by wtrocki** [comment]
@craicoverflow I have used lower case upper case etc. all failures :D

**Comment by craicoverflow** [comment]
I can see that the commit message in that pull request is using upper-case though. Try changing it.

**Comment by wtrocki** [comment]
I had that originally :)
This has nothing to do with the PR. I have I have 40 PR's failed in the row on various repositories :D

**Comment by craicoverflow** [comment]
I never experience this issue, so I think the tool is working fine.

**Comment by wtrocki** [comment]
ok.. Closing then
