### ISSUE TITLE
Inconsistency in service-registry examples

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#791]
## Description

Certain examples have references to old command `registry` instead of new command `service-registry`.

![Screenshot from 2021-07-02 18-18-05](https://user-images.githubusercontent.com/23582438/124276794-e548db80-db61-11eb-8a7f-849142a5f33e.png)

### Steps to reproduce

Add the steps required to reproduce this error.

1. Run the command `./rhoas service-registry -h`

**Comment by wtrocki** [comment]
working on it. Will add charmil rule to detect it

**Comment by wtrocki** [comment]
Fixed in https://github.com/redhat-developer/app-services-cli/pull/786
