### ISSUE TITLE
MK-test integration for service registry command

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#800]
MK-test integration for service registry command that will test creation/listing and deletion of services registries.

**Comment by wtrocki** [comment]
CC @b1zzu

**Comment by wtrocki** [comment]
@b1zzu What is your stance about this? Do you have any overlaping targets to support service registry backend and use CLI to create registry + artifacts?

**Comment by b1zzu** [comment]
@wtrocki yes we have a Jira task for it (not posting it here because is private), I can link this issue to the Jira task and we can close it together with the Jira task once is completed
