### ISSUE TITLE
Format command flag data types in command ref

### ISSUE THREAD

**Issue by bhardesty** [redhat-developer/app-services-cli#803]
### Feature or problem description

In the CLI command ref, the command flag data type is not formatted. For example, note the options here: https://github.com/redhat-developer/app-services-cli/blob/main/docs/commands/rhoas_cluster_bind.adoc

Instead of this:

**--app-name**
string Name of the kubernetes deployment to bind.

It would be better to format the data type on the same line as the flag name. For example (note the italics):

**--app-name _string_**
Name of the kubernetes deployment to bind.

### Proposed solution

Formatting the data type makes it easier to find and read the flag descriptions.

**Comment by wtrocki** [comment]
Can do :)

**Comment by bhardesty** [comment]
Just for reference, here's how that string should be formatted in asciidoc:

`` `--app-name _string_`:: ``
``Name of the kubernetes deployment to bind``

**Comment by bhardesty** [comment]
This was fixed as part of #819.
