### ISSUE TITLE
Write CLI guide that will match the UI workflow for Developer Persona

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#81]
Edit and improve documentation for CLI by providing documentation that provides number of steps that user can use to achieve some specific needs

Examples:
1. Logging and creating a cluster
2. Interacting with cluster - credentials and topics

Current guide:
https://github.com/bf2fc6cc711aee1a0c2a/cli/blob/main/website/docs/commands.md

**Comment by craicoverflow** [comment]
This is obsolete at this stage. Guides are in different repo now.
