### ISSUE TITLE
Inject rhoas version number into getting started guide

### ISSUE THREAD

**Issue by bhardesty** [redhat-developer/app-services-cli#826]
### Feature or problem description

In the "Getting started with the rhoas CLI" guide (https://github.com/redhat-developer/app-services-guides/tree/main/rhoas-cli), the `rhoas` version number is manually written, which requires manual updates every time a new version of `rhoas` is released. I've opened a PR to add a new doc attribute for this version number (https://github.com/redhat-developer/app-services-guides/pull/211). While this is an improvement, it still requires us to manually update the value of `{rhoas-version}` every time we release a new version of `rhoas`. 

### Proposed solution

If possible, automatically inject the rhoas version into the `{rhoas-version}` attribute whenever we release a new version of `rhoas`. The release number would need to be injected into the doc-attributes.adoc file, which is in the app-services-guides repo:
https://github.com/redhat-developer/app-services-guides/blob/e3e06cfc228f7ad85568b16624305ce81677f7e5/_artifacts/document-attributes.adoc#L15

### Additional context

An additional complication to consider: in the app-services-guides repo, all attributes are injected into each guide's README.adoc file. This means that if you change the value of the `{rhoas-version}` attribute, you also need to run the npm script to generate the attributes and open a PR.

**Comment by craicoverflow** [comment]
Thanks, it is a great idea. We could notify the guides repo whenever there has been a new release using [GitHub workflow events](https://docs.github.com/en/actions/reference/events-that-trigger-workflows). This could then trigger a job which would update the value of `{rhoas-version}`, and run the npm script to generate the attributes and open a PR. Perhaps we could auto-merge it?

**Comment by bhardesty** [comment]
Sounds like a great way to do this! Auto-merging would be great as long as we can be notified whenever a new version of the CLI is released (perhaps the standard CLI release announcements will be sufficient for this?). That's so we will know to make any adjustments to the attribute downstream.

**Comment by craicoverflow** [comment]
A pull request can still be created and the appropriate people can be tagged as a way of notifying - it can just be merged automatically before review.

**Comment by craicoverflow** [comment]
Actually given that there will be a time delay between the CLI being release upstream to when it is productixed and available on red Hat Infra, we should not merge automatically and it should be approved once is released to production.

**Comment by bhardesty** [comment]
Given the amount of manual intervention that will still be required, I wonder if this change is worth implementing. We can rework the version numbers in the CLI getting started guide to be as version-agnostic as possible so that we don't need to update the version number every release.

**Comment by craicoverflow** [comment]
I have it on the long term backlog, because I still think semi-automation is a good idea and it will remind us to keep it updated.

> We can rework the version numbers in the CLI getting started guide to be as version-agnostic as possible so that we don't need to update the version number every release.

Yeah we could try that. That is how I had structured the docs originally. For Linux and Mac, you don't really need to know the version number to download as you can just do: `curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh` but that will change completely when the CLI is productized and would be downloaded a completely different way, so maybe we should sit on this one for a while before changing anything?

**Comment by wtrocki** [comment]
I think this should be transfered to guides repo - we can action by removing versions from content

**Comment by bhardesty** [comment]
Agree that we can just remove/replace the version numbers. I created a new issue for it in app-services-guides instead of transferring it. I think we can close this one now.
