### ISSUE TITLE
CLI not working on Windows 10

### ISSUE THREAD

**Issue by EricWittmann** [redhat-developer/app-services-cli#828]
## Description

**Version**:  0.26.0-alpha5

Getting an error trying to run the CLI on Windows 10:  "open locales\en: file does not exist"

### Steps to reproduce

1. Download CLI for Windows
2. Run CLI, get error

![image](https://user-images.githubusercontent.com/1890703/126193708-4f47f6f4-64af-4259-9751-9f13723c095d.png)

**Comment by EricWittmann** [comment]
Also tested with 0.25.0 with the same result.

**Comment by wtrocki** [comment]
@rkpattnaik780 Do you have windows machine?

We should enable tests and build on windows for github actions in long run

**Comment by rkpattnaik780** [comment]
> @rkpattnaik780 Do you have windows machine?
Nope I have only linux here.
> We should enable tests and build on windows for github actions in long run
Yes, that will be great to have.

**Comment by wtrocki** [comment]
Looks like path problem:
https://github.com/redhat-developer/app-services-cli/blob/main/pkg/localize/goi18n/go_i18n.go#L47

We can fix it and verify in CI/CD

**Comment by wtrocki** [comment]
Replicated problem and identified issue. On PTO so looking if anyone else could make change.

CC @pmuir
