### ISSUE TITLE
Inconsistencies in punctuation of flag description

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#830]
## Current scenario

There are some inconsistencies regarding use of periods in flag descriptions. Some flags end with period and some don't. As suggested by @craicoverflow we shouldn't use periods as the flags provided by cobra (--default and --help) don't use them too.

![Screenshot from 2021-07-09 17-07-07](https://user-images.githubusercontent.com/23582438/126449564-a24c2832-9df5-478e-84ab-0be34084a73b.png)

## Proposal

Remove full stops from description of all flags.

**Comment by rkpattnaik780** [comment]
@bhardesty what's your take on this issue?

**Comment by ankithans** [comment]
can be tackled through Charmil validator in future! Will add a rule for this.
cc: @wtrocki

**Comment by rkpattnaik780** [comment]
> can be tackled through Charmil validator in future! Can add a rule for this.

Thanks @ankithans :). That will be great.

**Comment by wtrocki** [comment]
Great idea. We need to fix multiple commands that have missing descriptions etc. See #777

**Comment by bhardesty** [comment]
We should try to be consistent. However, some flag descriptions have multiple sentences, so they should end with a full stop. 

How do the "default" and "choose from" values work? I think they're generated by cobra and appended to the end of the flag description. Can you control the punctuation? Here's an example of a description with both:

```
-o, --output string
  Format in which to display the Kafka instance. Choose from: "json", "yml", "yaml" (default "json")
```
I'll raise this with the rest of the docs team next time that we meet, and report back with a recommendation.

**Comment by rkpattnaik780** [comment]
> Can you control the punctuation?
Seems the punctuation can be controlled.
Taking a quick look at other CLIs, full stops are not that popular with flags.

**Comment by wtrocki** [comment]
Checked couple clis. Punctuations aren't used for flags for those

**Comment by bhardesty** [comment]
To follow up, I think we can remove the periods. There are only a couple descriptions with multiple sentences, and I think they can be revised to just be a single sentence (without a period).
