### ISSUE TITLE
Show user when there is a new version available in every command, cached so that it is only shown once per version/day

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#841]
### Feature or problem description

Running `rhoas version` will also show if there is a version update available. This is intended so that users know to update their version to the latest. An issue with this is most users will not know there is an update available and will not check for it, we should highlight this in every command so that they instantly become aware.

### Proposed solution

Every time `rhoas` is executed, a version check is performed against the GitHub API. If the latest release is different to the user's release, and the version has not yet been checked for today, where the version == the latest release, then we should print this info to stderr. 

We might need to add a `metadata` object to the rhoas config:

```
"rhoas_metadata": {
  "dev_preview_enabled": true,
  "last_version_checked_at": "2021-07-26T10:00:04+00:00",
  "last_version_checked": "0.26.1"
}
```

**Comment by wtrocki** [comment]
I have discussed this with users of the CLI and there was also another feedback that debug command should be actually called verbose command. 

If debug becomes verbose then users will call it and should get version check in this as well.

**Comment by craicoverflow** [comment]
Would you mind creating a separate issue to discuss that?

**Comment by wtrocki** [comment]
Quick question would that resolve need for this issue? If we document that if something wrong happens with CLI use verbose mode. 
That will give you:

1) Exact and fully error from backend which should return you information that your API call is outdated
2) Check if the version is up to date and suggest new one
3) When error happens without `--verbose` we can have generic message that suggest user to use --verbose flag for more details.
4) user gets info when it is needed in context (not in 4 hours later when timer kicks in)

This is what I have seen in other CLI's 

We do not need to change debug to verbose if we print message (point nr3) so there is no big drawbacks.

**Comment by craicoverflow** [comment]
I think both can be done - I still think it is a good idea to check for a version and tell the user when there is no error - for instance to unlock new features.

GitHub CLI does this nicely:

![gh_update](https://user-images.githubusercontent.com/11743717/126973323-9fe17dd2-519a-4130-8dbf-9f5c2448fc35.png)

**Comment by wtrocki** [comment]
Agreed. Creating separate issue.

**Comment by wtrocki** [comment]
@craicoverflow You are assigned on this issue. What is the status?
