### ISSUE TITLE
Introduce verbose mode that is printed on every error 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#842]
## What

Rename debug to verbose flag for better alignment with other CLI's
Print verbose flag on errors (especially API errors). For example:
`To view more details use --verbose flag`
Verbose flag will also check for cli updates.

## Discussion from another issue

If we document that if something wrong happens with CLI use verbose mode. 
That will give us:

1) Exact and fully error from backend which should return you information that your API call is outdated
2) Check if the version is up to date and suggest new one
3) When error happens without `--verbose` we can have generic message that suggest user to use --verbose flag for more details.
4) user gets info when it is needed in context (not in 4 hours later when timer kicks in etc.)

This approach is what I have seen in other CLI's 

We do not need to change debug to verbose if we print message (point nr3) so there is no big drawbacks.

_Originally posted by @wtrocki in https://github.com/redhat-developer/app-services-cli/issues/841#issuecomment-886567606_

**Comment by craicoverflow** [comment]
The main reason we used `--debug` was because `-v` is already used to check the version. We could:

Remove the shorthand `-v` for `--version` so that `rhoas -v` is only used for verbose mode.

OR

Make `-v` call `version` only when used in the root command. For all subcommands it means verbose.

**Comment by wtrocki** [comment]
`-v` for version seams strange. I would expect command for it. Meaning:

`rhoas version` which is there. and -v can be shortcut for verbose. 

I can do investigations how other CLIs do it but most of the cobra ones come with this version command instead of flags

**Comment by wtrocki** [comment]
Also debug seems to be also widely used flag so if we print it after error then we can stick to debug and avoid breaking change/confusion - which I think is good. 

Example of debug not being trivial: 
https://github.com/microsoft/appcenter-cli/issues/646

**Comment by craicoverflow** [comment]
`-v` for version seams strange. I would expect command for it.

This comes out of the box with Cobra, so it must be pretty standard.
