### ISSUE TITLE
Missing client-side validation when decreasing a Kafka topic partition count

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#843]
## Description

**Version**: 0.26.0

It is not possible to to decrease the partition count of a Kafka topic. This validation is handled server-side, but we need to also have validation within the CLI for a better user experience.

### Steps to reproduce

1. Create a Kafka topic with 3 partitions: `rhoas kafka topic create topic-1 --partitions 3`
2. Try to decrease the partition count: `rhoas kafka topic update topic-1 --partitions 2`

You will see that the request is sent to the server and you will receive a `400: Bad Request`.

**Comment by rkpattnaik780** [comment]
Will it really make sense to make a server request to do a client side validation for non-interactive mode? This would cause a delay, is there any way we can make use of the server response here? [Earlier discussions](https://github.com/redhat-developer/app-services-cli/pull/823#issuecomment-882013987)

**Comment by craicoverflow** [comment]
I'm not sure I understand what you are asking. We should prevent a server request by having client-side validation to check the condition and stop the program if `newPartitionCount < oldPartitionCount` is not satisfied.

**Comment by rkpattnaik780** [comment]
I meant this will be similar to making a get request first to check if a topic exist and then proceeding to delete the topic.

1. Run `./rhoas kafka topic delete <name>`
2. CLI first does a getTopic to check if topic exists.
3. If response is `200`, a request is again made for deleteTopic.

But we omit the second step and let deleteTopic determine if topic exists. I was thinking we should have something similar for topic update.

**Comment by craicoverflow** [comment]
Okay yes, sorry I understand now and forgot that we would need to fetch the topic first. You are right.

**Comment by craicoverflow** [comment]
> is there any way we can make use of the server response here?

The server should really be using the more accurate status message when it is available.

**Comment by craicoverflow** [comment]
Okay so I have created a PR to assign every error in the kafka-admin-api to the Error schema. This should give the CLI access to this schema and we can use the error message from the response body.
