### ISSUE TITLE
open locales\en: file does not exist

### ISSUE THREAD

**Issue by UlrichGiorgioJaeger** [redhat-developer/app-services-cli#856]
hi after installation for windows like in documentation and adding it to path and then try to run C:\rhoas\rhoas --version it prints out always the following message open locales\en: file does not exist.

What can i do ? Can you help?

**Comment by wtrocki** [comment]
We also noticed another issue #857 

Current workaround for it is to login using token:

rhoas login --token=token

Where token comes from https://cloud.redhat.com/openshift/token

**Comment by UlrichGiorgioJaeger** [comment]
ok tried the latest 0.27 version still same issue.

**Comment by wtrocki** [comment]
@UlrichGiorgioJaeger This one: https://github.com/redhat-developer/app-services-cli/releases/tag/v0.27.0-alpha1

**Comment by UlrichGiorgioJaeger** [comment]
ok now it worked 

rhoas version 0.27.0-alpha1

allright

**Comment by wtrocki** [comment]
Closing. Our team will look into login issue today. Till then please use workaround
