### ISSUE TITLE
Cannot login in windows

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#857]
## Description

When logging in windows using latest version of CLI I get:
```
Failed to verify ID Token: oidc: token is expired (Token Expiry: 2021-07-30 10:17:46 +0100 BST)
```
 

### Steps to reproduce
0. Install rhoas cli on your system (download binary https://github.com/redhat-developer/app-services-cli/releases/tag/v0.27.0-alpha1) 
1. Execute rhoas login
2. View error in browser (after you log in)

**Comment by wtrocki** [comment]
CC @pmuir

**Comment by wtrocki** [comment]
Current workaround for it is to login using token:

rhoas login --token=token

Where token comes from https://cloud.redhat.com/openshift/token

**Comment by craicoverflow** [comment]
I have tested logging in on Windows 10 using multiple scenarios and environments and could not reproduce this error.

Latest development version:
![image](https://user-images.githubusercontent.com/11743717/128355662-dd68d887-7417-4921-9ec3-7985be7afb2f.png)

Command Prompt (0.27.0-alpha1):
![image](https://user-images.githubusercontent.com/11743717/128355881-024e56b0-b12a-4607-8187-693e23489208.png)

Powershell (0.27.0-alpha1):
![image](https://user-images.githubusercontent.com/11743717/128356182-fd642100-993e-4f85-990c-8bc8d5530064.png)
