### ISSUE TITLE
Enable dev preview feature as environment variable

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#873]
### Feature or problem description

Use some env variable to detect that dev mode is enabled. 
Document usage in contributing guide and releases. 

```
export RHOAS_ENABLE_DEVELOPMENT_FEATURES=true
```

**Comment by bhardesty** [comment]
Will this also remove the "rhoas config dev-preview" command?

**Comment by wtrocki** [comment]
Yes. Forgot to mention it in ticket

**Comment by wtrocki** [comment]
After sync with  @craicoverflow we have following targets:

- rhoas config dev-preview will be removed along with config command (no use for it)
- dev preview functionality will stay for printing labels for services (no enablement needed)
- we will add env var

**Comment by wtrocki** [comment]
done in #908 (blocked merge)
