### ISSUE TITLE
Interactive mode for `consumer-group reset-offset`

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#877]
### Feature or problem description

User should be able to reset offset for a consumer group via prompt.

### Proposed solution

`rhoas consumer-group reset-offset`

### Additional context

Should the interactive mode be similar to non-interactive one? Currently the CLI is supposed to allow only one specific topic as flags: 

> --topic topic-1 --partitions "0 1"

Interactive mode is bit flexible on this part, it should be easy to implement something like this:

```
> Enter topic name: 
topic-1
> Enter partitions:
"0 1"
> Want to add another topic (y/N)?
y
> Enter topic name: 
topic-2
> Enter partitions:
"0 2"
> Want to add another topic (y/N)?
n
> Enter value:
```

Will this be something we'd like to have?

Enhancement of #763

**Comment by wtrocki** [comment]
My take is that interactive mode should land with features (PR's) 
For this particular use case, I do not think this is useful as this command is potentially harmful and mistype in interactive mode (or potential stdin bug)  can affect it.

**Comment by craicoverflow** [comment]
> My take is that interactive mode should land with features (PRs)

Interactive mode is less important than non-interactive, so I would not say this must always be the case, especially when there might be time pressure or if it would make the pull request too large.

I had not really considered that this command might need interactive mode. What would be the additional benefit to the user if this were to be added?

**Comment by rkpattnaik780** [comment]
Interactive mode will allow user to reset offset for multiple topics, I have explained the flow in `Additional Context` of the issue.

**Comment by craicoverflow** [comment]
Ah yes I understand the difference now after re-reading, sorry. Will the UI allow you to select multiple topics in a bulk offset reset operation? I think this is a nice idea, but the UX should be implemented carefully to make it very difficult to select the wrong values.

**Comment by rkpattnaik780** [comment]
UI is not as flexible as CLI. UI has `topic` as required field (one topic is required), however in CLI we can skip `--topic` and reset all consumers. In interactive mode we can pass multiple topics, with respective partitions. This is something api supports.

**Comment by craicoverflow** [comment]
> however in CLI we can skip --topic and reset all consumers.

This is a destructive action and the user could be expecting to have to specify a topic, especially if this is the expected behaviour of the UI. It might be better to explicitly "opt-in" to resetting topic offsets. What you think?

**Comment by wtrocki** [comment]
@craicoverflow Agreed. I did not clarified myself properly. 
As for actual reset - I'm really worried that user might just run this command without reading docs and cause some unexpected actions. This command is special - it is not like create that you can later remove or correct. Resetting wrong thing might cause data loss etc. 

My ideal scenario will be that user reads extensive documentation for the commands and pick flags to execute non interactively. We cannot pass that much info or side effects in interactive mode sadly.

**Comment by craicoverflow** [comment]
We have other destructive commands such as `topic delete`, `kafka delete` etc. Provided there is a confirmation at the end which clearly outlines what action is about to be performed, along with the consequences this should be okay.

I don't see how interactive mode is more risky than using just flags though. Can you explain a bit more what exactly could go wrong?

> mistype in interactive mode (or potential stdin bug)

Both of these scenarios are also possible in non-interactive mode. With a prompt you get live visual feedback which would show what values you have entered so it could even be more safe.

**Comment by wtrocki** [comment]
I'm leaving this topic for you guys :D

**Comment by rkpattnaik780** [comment]
> This is a destructive action and the user could be expecting to have to specify a topic, especially if this is the expected behaviour of the UI. It might be better to explicitly "opt-in" to resetting topic offsets. What you think?

We can probably go with `--topic` as required then and propose `reset-all` to UI. We can do modifications later if needed.

**Comment by wtrocki** [comment]
My vote would be to look for user feedback and close it for now. WDYT?
