### ISSUE TITLE
`IntVar` should be used instead of `IntVarP` when shorthand is not needed

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#897]
## Description

For certain commands, `IntVar` and `IntVarP` are used interchangeably (can be applied to other types too). We should use _Var when no shorthand is required.

**Comment by nickmancari** [comment]
I can work on this. Want me to check BoolVarP and StringVarP usage as well? I see a lot of instances where StringVarP is used with empty shorthand parameters.

**Comment by wtrocki** [comment]
@nickmancari Yes. That will be great

**Comment by wtrocki** [comment]
Ping me in case of issues

**Comment by nickmancari** [comment]
Will do. Thanks
