### ISSUE TITLE
Improve description of the service registry command

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#901]

**Comment by wtrocki** [comment]
Another feedback:

```
The help text for “artifacts” could perhaps be better, to indicate that it’s the command used to manipulate data stored in the currently “selected” registry instance.
```

**Comment by bhardesty** [comment]
@smccarthy-ie FYI, you might want to review/update the service registry command description.

**Comment by wtrocki** [comment]
@bhardesty Sorry for the invalid ping. I will ping @smccarthy-ie from now on for service registry content.

**Comment by wtrocki** [comment]
Closing. Content for registry is stil in the works as we did not pulled any strings into i18n
Once that is done I will exclusively ping @smccarthy-ie for review (currently review will involve reviewing codebase which is not ideal). Issue to watch #904
