### ISSUE TITLE
Add dump print helper to all commands.

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#905]
### Feature or problem description

Currently we are replicating a lot of code across the commands to print based on the output format. 
We should use helper in the dump package (available currently in the PR #859)

**Comment by craicoverflow** [comment]
https://github.com/redhat-developer/app-services-cli/blob/20d25bd0777e462cb71e95232bf48ccf56835221/pkg/dump/dump.go#L141

Helper has been added, just needs to be applied in the commands which use the dump.YAML and dump.JSON methods.

**Comment by craicoverflow** [comment]
`PrintDataInFormat` should ideally return the error though - this should not be ignored within the method.
