### ISSUE TITLE
Extract Artifacts commands to the Apicurio CLI

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#907]
### Feature or problem description

 We need to investigate how it will be possible to extract artifacts commands out of the RHOAS CLI 
and use them in standalone CLI. Investigation can be done outside our codebase. 

We should identify a number of missing points that are required to run artifacts as standalone CLI using Charmil.

Assigning @ankithans members as we are actually having the same goals in charm and this is not time-sensitive task.

**Comment by ankithans** [comment]
yes assign me.

**Comment by wtrocki** [comment]
Closing as stale. We want to refactor code in rhoas repository first and then form proper charmil core implementation
