### ISSUE TITLE
Interactive mode for use commands

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#922]
Service registry and other  control plane services should provide interactive mode for use command

**Comment by craicoverflow** [comment]
I think this exists for the `kafka use` command already, right? We should totally use it everywhere though.

By the way - the `needs-triage` label will not get added when an issue does not have a body.

**Comment by wtrocki** [comment]
Will add proper descriptions from now on. Yes. This issue is about copying what we have for kafka.
