### ISSUE TITLE
Registry commands should not use positionals

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#923]
Feedback

```
I’m not sure I like the fact that some commands have positional arguments that don’t need to be passed with a flag.  So for example you can do this:

rhoas service-registry artifact list TestGroup

Or you can do this:

rhoas service-registry artifact list -g TestGroup

It’s not clear to me from the CLI “Flags” help text that I can do that.  It is sometimes made clear from the examples, but not always.  I don’t have a strong opinion here, but I think it makes more sense if every parameter needs to be passed using a flag. 

```

**Comment by craicoverflow** [comment]
If we decided to no longer use positionals, I'm fine with that, but we would need to apply this across the board.

**Comment by craicoverflow** [comment]
This change could be kept backwards-compatible by adding a `--name` flag, but that would be confusing for someone entering `rhoas service-registry use my-registry --name=my-registry2`.

**Comment by wtrocki** [comment]
Yes. We need to add --name flag.

**Comment by wtrocki** [comment]
Actually comments here were specific to artifacts. 

Using positional for:

- name
- file

is ok and generally this is the most common use case across entire cli. 
So this issue is more specific to artifacts CLI (separate issue for use command will cover other cases)
