### ISSUE TITLE
Service registry instance should be specified by name as long as id.

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#924]
```
Is there any way we could also allow the name of an instance to be used in the “--id” flag for commands that support “--id”?  Perhaps if the value is an integer it can be used as-is, but if it’s not then the CLI can lookup the instance ID (int) from the string?

```

**Comment by craicoverflow** [comment]
That could be very confusing as it would not be clear that the `--id` flag accepts the name. This is also inconsistent with the current CLI style so it would be a divergence from the user experience.

**Comment by wtrocki** [comment]
instance-id is used to customize registry (we need issue for global customization as there were some confusion but things were not implemented)

Having two functional flags that exclude each other might be confusing. Closing
