### ISSUE TITLE
rhoas service-registry use and kafka use has inconsistent flag and positional implementation

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#927]
Feedback

```
The command allows the name of the registry instance to be included in the base command but required the id of the instance when using the “--id” flag:
Works: rhoas service-registry use ewittman
Works: rhoas service-registry use --id 3
Does not work: rhoas service-registry use 3
Does not work: rhoas service-registry --id ewittman
Note: this is fine but should be made clear in the help text, which indicates “<id>” in both cases.
```

**Comment by wtrocki** [comment]
CC @craicoverflow

**Comment by craicoverflow** [comment]
https://github.com/redhat-developer/app-services-cli/blob/f8cd89d6305cdc1d507d947acd95d0babd29184f/pkg/localize/locales/en/cmd/registry_crud.en.toml#L92-L95

The example for this command is invalid.

**Comment by wtrocki** [comment]
I think we have 2 issues here:

1) we need to add --name flag to kafka and registry use command
2) we should not have any positional support for use (docs issue)

**Comment by wtrocki** [comment]
Triaged with @craicoverflow and @rkpattnaik780
