### ISSUE TITLE
Global --version flag clashes with the service registry artifacts get --version flag

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#931]
### Feature or problem description

Do we actually need --version flag considering that we have version command?

**Comment by craicoverflow** [comment]
The main reason for having both is that both are very common. Many developers have personal preferences of one over the other and so it would come naturally for them to use it regularly. 

![Screenshot from 2021-08-19 09-40-20](https://user-images.githubusercontent.com/11743717/130037610-507822e0-45dd-4357-a40c-0a579336a912.png)

I'd like to keep it. But we can avoid this clash by only allowing `--version` to exist on the root command (right now it is global and so is clashing).

**Comment by wtrocki** [comment]
@craicoverflow functionality wise there is no clash. Problem is that --version is just printed in help as global along with --version for the commands.  


1) rename artifacts --version to something else (--version-number, --version-id, --version-ref)

This is going to make this argument overly long

2)  
> But we can avoid this clash by only allowing --version to exist on the root command (right now it is global and so is clashing).

That will be my prefference
