### ISSUE TITLE
Missing flags for rhoas service-registry artifact metadata

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#932]
```
rhoas service-registry artifact metadata 
Need a way to update meta-data (name, description, labels, properties)
Need a way to specify a version (optional)
```

**Comment by wtrocki** [comment]
We need to get this done before release

**Comment by wtrocki** [comment]
CC @craicoverflow @rkpattnaik780 looking for your stance on commands layout
Requirements is to be able to edit metadata and fetch it. This is typically done by two commands

1) Model without group
```
rhoas service-registry artifact get-metadata 
rhoas service-registry artifact set-metadata 
```

2) Metadata as group

```
rhoas service-registry artifact metadata get
rhoas service-registry artifact metadata set
```
3) Metadata flags (terrible idea)

**Comment by wtrocki** [comment]
I personally like 1.2)

**Comment by rkpattnaik780** [comment]
`2` looks good to me.

**Comment by craicoverflow** [comment]
I personally like 1.

Why `get/set` instead of `describe/update`?

**Comment by wtrocki** [comment]
` get/set` were just operation names. Can do describe/update no problem

**Comment by craicoverflow** [comment]
Is the main reason for joining the words to reduce the number of subcommands?

> Generally for dataplane commands we might need to be less strict about crud command names as context might be different.

Actually that is 100% true.

**Comment by wtrocki** [comment]
> Is the main reason for joining the words to reduce the number of subcommand?

Yes. Not sure if you like it. The reason for it is that it reduces number of tab in autocompletion and minimizes number of chars to type when autocompletion is not enabled.
