### ISSUE TITLE
Release tarballs don't contain ./docs

### ISSUE THREAD

**Issue by cben** [redhat-developer/app-services-cli#940]
## Description

Consider including docs/ in release tarballs.

**Version**: rhoas_0.27.0-alpha3_linux_amd64.tar.gz, rhoas_0.27.0-alpha3_windows_amd64.zip

### Steps to reproduce

1. Get Linux tarball or Windows .zip from [GitHub releases](https://github.com/redhat-developer/app-services-cli/releases).
2. Unpack tarball/zip.
3. Open README.md
4. It refers to ./docs and ./CONTRIBUTING.md that are not in the tarball.  It does not even link back to the GitHub repository.

### Expected vs actual behaviour

The "broken links" in this context are obviously nitpicking :wink:.  But it's more confusing for users that get the tarball via [OCM Downloads page](https://console.redhat.com/openshift/downloads), they never visited this repo.
(BTW, I'm maintaining that page.)

One fix it to use absolute https://github.com/... links in the README.
But maybe a more user-friendly answer is to bundle the docs with the tool, same way command distributions typically come with manpages or some other docs...

Are the docs equivalent to outputs you can get from `rhoas --help`?  
If yes, maybe no point including them, but better say so in the README e.g.
> Run `rhoas help` for command reference.

- BTW, the rpm is even worse — currently has `/usr/bin/rhoas` and nothing else, not even a license or link back to the source.  Aside from improving that, consider linking back to the repo from `rhoas version` or `rhoas help` output.

**Comment by craicoverflow** [comment]
Thanks for logging these issues @cben!

> Are the docs equivalent to outputs you can get from `rhoas --help`?

Yes, the command-line reference docs are the exact same as the docs available via the help flag.

> One fix it to use absolute github.com... links in the README.

I think that might be a good quick fix for this.

> But maybe a more user-friendly answer is to bundle the docs with the tool, same way command distributions typically come with manpages or some other docs...

We could do that, although it does not seem very typical. Another option would be too not include the README along with the tarball?

**Comment by wtrocki** [comment]
update on this?

**Comment by craicoverflow** [comment]
Since we are working on the productized CLI, this will become less of an issue. We could still remove the README fron the upstream release folders though. Let's have this as a good first issue.
