### ISSUE TITLE
Check error in dynamic flag completion results and log an error in debug mode

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#966]
These three places we are fetching data from an API to populate the flag completion values:

https://github.com/redhat-developer/app-services-cli/blob/33219ceec41eba2e64cacb71e8e9f74135744c51/pkg/cmd/kafka/describe/describe.go#L87
https://github.com/redhat-developer/app-services-cli/blob/33219ceec41eba2e64cacb71e8e9f74135744c51/pkg/cmd/kafka/delete/delete.go#L87
https://github.com/redhat-developer/app-services-cli/blob/f25528215ade451f12b16094a7e284ae77b4595b/pkg/cmd/kafka/use/use.go#L70

We are ignoring the error though, which is highly possible. We should log this error in **debug** mode. It is fine if there is an error as the flag will still work, but it can be a useful addition.

Requires https://github.com/redhat-developer/app-services-cli/issues/914 to be completed first.

**Comment by alexal** [comment]
@craicoverflow I would love to work on this as well as on #914.
