### ISSUE TITLE
Review all service-registry i18n strings

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#973]
## Description

I have noticed that there are some service registry i18n strings which are invalid.

One such example:

https://github.com/redhat-developer/app-services-cli/blob/a1524be3d3f2f538618779e5bd61e45279efe9a1/pkg/localize/locales/en/cmd/registry_crud.en.toml#L122-L124

The text of this string explicitly refers to the deletion of a registry instance, but this is used in both the `delete` and `describe` commands. I have some other similar cases. These should be reviewed and fixed.

**Comment by wtrocki** [comment]
Done. I could not find any other issues - having a single file for all registry was quite helpful with review
