### ISSUE TITLE
Add a timeout when logging in via the web browser

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#989]
The `login` command should have a timeout so that it does not "hang" if the command fails.

**Comment by alexal** [comment]
@craicoverflow I would like to work on this if you do not mind.

**Comment by craicoverflow** [comment]
That would be great @alexal!

**Comment by alexal** [comment]
@craicoverflow , the code is ready. I have three questions for you:

1. How big should be the default timeout? 60 seconds will be enough?
2. What error message should be returned when timeout is reached?
3. Do you want to me wait until #982 is merged to avoid changing TOML files?

**Comment by craicoverflow** [comment]
> @craicoverflow , the code is ready. I have three questions for you:
> 
> 1. How big should be the default timeout? 60 seconds will be enough?

I think 60 is probably too much. Let's go with 30.

> 2. What error message should be returned when timeout is reached?

"login attempt has expired"

> 3. Do you want to me wait until [refactor: converted i18n files from TOML to YAML #982](https://github.com/redhat-developer/app-services-cli/pull/982) is merged to avoid changing TOML files?

You can go ahead with this PR, we have decided to not go ahead with the YAML i18n files. Thanks.

**Comment by alexal** [comment]
@craicoverflow thanks, please review PR #991 .
