### ISSUE TITLE
Cli should use custom user agent when making requests to all SDK

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#994]
## Description

See Connection structure that does define all APIs. 

When building API objects we need to override User-Agent with RHOAS CLI name and it's version.

**Comment by wtrocki** [comment]
Example: 
https://github.com/redhat-developer/app-services-cli/blob/metadata/pkg/connection/keycloak_connection.go#L366:L366

> 	cfg.UserAgent = "rhoas-cli_" + version

**Comment by alexal** [comment]
@wtrocki I would like to work on this one if you do not mind.

**Comment by wtrocki** [comment]
@alexal Actually this sounds like bug on go SDK: We do not expose ability there to setup custom user agent (or anything in the config). We  need to triage this issue first with @craicoverflow

**Comment by craicoverflow** [comment]
> We do not expose the ability there to set up a custom user agent (or anything in the config).

Yeah we can just add this new field to the SDK config.

**Comment by wtrocki** [comment]
SO actually this would be 2 PRs:

1) In https://github.com/redhat-developer/app-services-sdk-go to add agent to every config field
2) Then use agent in the CLI

@alexal this is still for grabs if you want to

**Comment by alexal** [comment]
@wtrocki yes

**Comment by alexal** [comment]
@wtrocki please review the first one here https://github.com/redhat-developer/app-services-sdk-go/pull/259
