### ISSUE TITLE
Unified suggestions for use, create, update, delete flags (id and name)

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#999]
### Feature or problem description

We have number of commands now that provide set of flags: --name, --id. We can easily provide shell extensions for those flags (as we do in some of the commands)

**Comment by craicoverflow** [comment]
Can you explain a bit more what you mean by "suggestions" - dynamic completions?

**Comment by wtrocki** [comment]
When typing --id= and pressing tab we want to have command line suggestions that are common with filesystem items:
<img width="1505" alt="Screenshot 2021-08-31 at 14 09 50" src="https://user-images.githubusercontent.com/981838/131508222-be4eb593-317b-42d3-875e-7d24a523296c.png">

**Comment by craicoverflow** [comment]
Thanks, that is what I thought, just confirming.
